var searchData=
[
  ['case',['CASE',['../structstxxl_1_1CASE.html',1,'stxxl']]],
  ['choose',['choose',['../classstxxl_1_1stream_1_1choose.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_201_20_3e',['choose&lt; Input, 1 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_011_01_4.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_202_20_3e',['choose&lt; Input, 2 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_012_01_4.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_203_20_3e',['choose&lt; Input, 3 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_013_01_4.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_204_20_3e',['choose&lt; Input, 4 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_014_01_4.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_205_20_3e',['choose&lt; Input, 5 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_015_01_4.html',1,'stxxl::stream']]],
  ['choose_3c_20input_2c_206_20_3e',['choose&lt; Input, 6 &gt;',['../classstxxl_1_1stream_1_1choose_3_01Input_00_016_01_4.html',1,'stxxl::stream']]],
  ['choose_5fint_5ftypes',['choose_int_types',['../structstxxl_1_1choose__int__types.html',1,'stxxl']]],
  ['choose_5fint_5ftypes_3c_204_20_3e',['choose_int_types&lt; 4 &gt;',['../structstxxl_1_1choose__int__types_3_014_01_4.html',1,'stxxl']]],
  ['choose_5fint_5ftypes_3c_208_20_3e',['choose_int_types&lt; 8 &gt;',['../structstxxl_1_1choose__int__types_3_018_01_4.html',1,'stxxl']]],
  ['choose_5fint_5ftypes_3c_20my_5fpointer_5fsize_20_3e',['choose_int_types&lt; my_pointer_size &gt;',['../structstxxl_1_1choose__int__types.html',1,'stxxl']]],
  ['cmdline_5fparser',['cmdline_parser',['../classstxxl_1_1cmdline__parser.html',1,'stxxl']]],
  ['cmp',['Cmp',['../structstxxl_1_1hash__map_1_1hash__map_1_1Cmp.html',1,'stxxl::hash_map::hash_map']]],
  ['cmp',['cmp',['../structstxxl_1_1addressable__priority__queue_1_1cmp.html',1,'stxxl::addressable_priority_queue']]],
  ['column_5fvector',['column_vector',['../classstxxl_1_1column__vector.html',1,'stxxl']]],
  ['compat_5fhash',['compat_hash',['../structstxxl_1_1compat__hash.html',1,'stxxl']]],
  ['compat_5fhash_5fmap',['compat_hash_map',['../structstxxl_1_1compat__hash__map.html',1,'stxxl']]],
  ['compat_5fhash_5fmap_3c_20bid_5ftype_2c_20busy_5fentry_2c_20bid_5fhash_20_3e',['compat_hash_map&lt; bid_type, busy_entry, bid_hash &gt;',['../structstxxl_1_1compat__hash__map.html',1,'stxxl']]],
  ['compat_5fhash_5fmap_3c_20bid_5ftype_2c_20unsigned_5ftype_2c_20bid_5fhash_20_3e',['compat_hash_map&lt; bid_type, unsigned_type, bid_hash &gt;',['../structstxxl_1_1compat__hash__map.html',1,'stxxl']]],
  ['compat_5fhash_5fmultimap',['compat_hash_multimap',['../structstxxl_1_1compat__hash__multimap.html',1,'stxxl']]],
  ['compat_5fhash_5fmultimap_3c_20internal_5fsize_5ftype_2c_20iterator_5fbase_20_2a_2c_20hasher_20_3e',['compat_hash_multimap&lt; internal_size_type, iterator_base *, hasher &gt;',['../structstxxl_1_1compat__hash__multimap.html',1,'stxxl']]],
  ['compat_5funique_5fptr',['compat_unique_ptr',['../structstxxl_1_1compat__unique__ptr.html',1,'stxxl']]],
  ['compat_5funique_5fptr_3c_20buf_5fistream_5ftype_20_3e',['compat_unique_ptr&lt; buf_istream_type &gt;',['../structstxxl_1_1compat__unique__ptr.html',1,'stxxl']]],
  ['compat_5funique_5fptr_3c_20stxxl_3a_3acompletion_5fhandler_5fimpl_20_3e',['compat_unique_ptr&lt; stxxl::completion_handler_impl &gt;',['../structstxxl_1_1compat__unique__ptr.html',1,'stxxl']]],
  ['compat_5funique_5fptr_3c_20stxxl_3a_3astxxl_3a_3aio_5ferror_20_3e',['compat_unique_ptr&lt; stxxl::stxxl::io_error &gt;',['../structstxxl_1_1compat__unique__ptr.html',1,'stxxl']]],
  ['completion_5fhandler',['completion_handler',['../classstxxl_1_1completion__handler.html',1,'stxxl']]],
  ['completion_5fhandler1',['completion_handler1',['../classstxxl_1_1completion__handler1.html',1,'stxxl']]],
  ['completion_5fhandler_5fimpl',['completion_handler_impl',['../classstxxl_1_1completion__handler__impl.html',1,'stxxl']]],
  ['compute_5fn',['compute_N',['../structstxxl_1_1priority__queue__local_1_1compute__N.html',1,'stxxl::priority_queue_local']]],
  ['compute_5fn_3c_201_2c_20x_5f_2c_20criticalsize_5f_20_3e',['compute_N&lt; 1, X_, CriticalSize_ &gt;',['../structstxxl_1_1priority__queue__local_1_1compute__N_3_011_00_01X___00_01CriticalSize___01_4.html',1,'stxxl::priority_queue_local']]],
  ['compute_5fsorted_5fruns_5ftype',['compute_sorted_runs_type',['../classstxxl_1_1stream_1_1compute__sorted__runs__type.html',1,'stxxl::stream']]],
  ['concatenate',['concatenate',['../classstxxl_1_1stream_1_1concatenate.html',1,'stxxl::stream']]],
  ['condition_5fvariable',['condition_variable',['../classstxxl_1_1condition__variable.html',1,'stxxl']]],
  ['config',['config',['../classstxxl_1_1config.html',1,'stxxl']]],
  ['const_5fcounting_5fptr',['const_counting_ptr',['../classstxxl_1_1const__counting__ptr.html',1,'stxxl']]],
  ['const_5fdeque_5fiterator',['const_deque_iterator',['../classstxxl_1_1const__deque__iterator.html',1,'stxxl']]],
  ['const_5fmatrix_5fcol_5fmajor_5fiterator',['const_matrix_col_major_iterator',['../classstxxl_1_1const__matrix__col__major__iterator.html',1,'stxxl']]],
  ['const_5fmatrix_5fiterator',['const_matrix_iterator',['../classstxxl_1_1const__matrix__iterator.html',1,'stxxl']]],
  ['const_5fmatrix_5frow_5fmajor_5fiterator',['const_matrix_row_major_iterator',['../classstxxl_1_1const__matrix__row__major__iterator.html',1,'stxxl']]],
  ['const_5fvector_5fiterator',['const_vector_iterator',['../classstxxl_1_1const__vector__iterator.html',1,'stxxl']]],
  ['counted_5fobject',['counted_object',['../classstxxl_1_1counted__object.html',1,'stxxl']]],
  ['counter',['counter',['../structstxxl_1_1stream_1_1counter.html',1,'stxxl::stream']]],
  ['counting_5fptr',['counting_ptr',['../classstxxl_1_1counting__ptr.html',1,'stxxl']]],
  ['counting_5fptr_3c_20request_20_3e',['counting_ptr&lt; request &gt;',['../classstxxl_1_1counting__ptr.html',1,'stxxl']]],
  ['counting_5fptr_3c_20sorted_5fruns_5fdata_5ftype_20_3e',['counting_ptr&lt; sorted_runs_data_type &gt;',['../classstxxl_1_1counting__ptr.html',1,'stxxl']]],
  ['counting_5fptr_3c_20swappable_5fblock_5fmatrix_5ftype_20_3e',['counting_ptr&lt; swappable_block_matrix_type &gt;',['../classstxxl_1_1counting__ptr.html',1,'stxxl']]]
];
