var searchData=
[
  ['bad_5fext_5falloc',['bad_ext_alloc',['../classstxxl_1_1bad__ext__alloc.html',1,'stxxl']]],
  ['bad_5fparameter',['bad_parameter',['../classstxxl_1_1bad__parameter.html',1,'stxxl']]],
  ['basic_5fallocation_5fstrategy',['basic_allocation_strategy',['../structstxxl_1_1basic__allocation__strategy.html',1,'stxxl']]],
  ['basic_5fruns_5fcreator',['basic_runs_creator',['../classstxxl_1_1stream_1_1basic__runs__creator.html',1,'stxxl::stream']]],
  ['basic_5fruns_5fcreator_3c_20stream_3a_3ause_5fpush_3c_20valuetype_20_3e_2c_20cmp_5ftype_2c_20blocksize_2c_20alloc_5fstrategy_5ftype_20_3e',['basic_runs_creator&lt; stream::use_push&lt; ValueType &gt;, cmp_type, BlockSize, alloc_strategy_type &gt;',['../classstxxl_1_1stream_1_1basic__runs__creator.html',1,'stxxl::stream']]],
  ['basic_5fruns_5fmerger',['basic_runs_merger',['../classstxxl_1_1stream_1_1basic__runs__merger.html',1,'stxxl::stream']]],
  ['basic_5fruns_5fmerger_3c_20sorted_5fruns_5ftype_2c_20comparetype_2c_20allocstr_20_3e',['basic_runs_merger&lt; sorted_runs_type, CompareType, AllocStr &gt;',['../classstxxl_1_1stream_1_1basic__runs__merger.html',1,'stxxl::stream']]],
  ['basic_5fruns_5fmerger_3c_20typename_20runs_5fcreator_5ftype_3a_3asorted_5fruns_5ftype_2c_20cmp_5ftype_2c_20alloc_5fstrategy_5ftype_20_3e',['basic_runs_merger&lt; typename runs_creator_type::sorted_runs_type, cmp_type, alloc_strategy_type &gt;',['../classstxxl_1_1stream_1_1basic__runs__merger.html',1,'stxxl::stream']]],
  ['batch_5fentry',['batch_entry',['../structstxxl_1_1buffered__writer_1_1batch__entry.html',1,'stxxl::buffered_writer']]],
  ['batch_5fentry_5fcmp',['batch_entry_cmp',['../structstxxl_1_1buffered__writer_1_1batch__entry__cmp.html',1,'stxxl::buffered_writer']]],
  ['bid',['BID',['../structstxxl_1_1BID.html',1,'stxxl']]],
  ['bid_3c_200_20_3e',['BID&lt; 0 &gt;',['../structstxxl_1_1BID_3_010_01_4.html',1,'stxxl']]],
  ['bid_3c_20block_5fsize_20_3e',['BID&lt; block_size &gt;',['../structstxxl_1_1BID.html',1,'stxxl']]],
  ['bid_3c_20raw_5fsize_20_3e',['BID&lt; raw_size &gt;',['../structstxxl_1_1BID.html',1,'stxxl']]],
  ['bid_5fcomp',['bid_comp',['../structstxxl_1_1btree_1_1iterator__map_1_1bid__comp.html',1,'stxxl::btree::iterator_map']]],
  ['bid_5feq',['bid_eq',['../structstxxl_1_1hash__map_1_1block__cache_1_1bid__eq.html',1,'stxxl::hash_map::block_cache']]],
  ['bid_5fhash',['bid_hash',['../structstxxl_1_1btree_1_1node__cache_1_1bid__hash.html',1,'stxxl::btree::node_cache']]],
  ['bid_5fhash',['bid_hash',['../structstxxl_1_1hash__map_1_1block__cache_1_1bid__hash.html',1,'stxxl::hash_map::block_cache']]],
  ['bid_5fhash',['bid_hash',['../structstxxl_1_1prefetch__pool_1_1bid__hash.html',1,'stxxl::prefetch_pool']]],
  ['bid_5fsequence',['bid_sequence',['../classstxxl_1_1stable__ksort__local_1_1bid__sequence.html',1,'stxxl::stable_ksort_local']]],
  ['bid_5fvector',['bid_vector',['../classstxxl_1_1vector_1_1bid__vector.html',1,'stxxl::vector']]],
  ['bidarray',['BIDArray',['../classstxxl_1_1BIDArray.html',1,'stxxl']]],
  ['bidarray_3c_20block_5ftype_3a_3araw_5fsize_20_3e',['BIDArray&lt; block_type::raw_size &gt;',['../classstxxl_1_1BIDArray.html',1,'stxxl']]],
  ['binary_5fbuffer',['binary_buffer',['../classstxxl_1_1binary__buffer.html',1,'stxxl']]],
  ['binary_5fbuffer_5fref',['binary_buffer_ref',['../classstxxl_1_1binary__buffer__ref.html',1,'stxxl']]],
  ['binary_5freader',['binary_reader',['../classstxxl_1_1binary__reader.html',1,'stxxl']]],
  ['block_5fcache',['block_cache',['../classstxxl_1_1hash__map_1_1block__cache.html',1,'stxxl::hash_map']]],
  ['block_5fcache_3c_20block_5ftype_20_3e',['block_cache&lt; block_type &gt;',['../classstxxl_1_1hash__map_1_1block__cache.html',1,'stxxl::hash_map']]],
  ['block_5fcache_5fwrite_5fbuffer',['block_cache_write_buffer',['../classstxxl_1_1hash__map_1_1block__cache__write__buffer.html',1,'stxxl::hash_map']]],
  ['block_5fcache_5fwrite_5fbuffer_3c_20block_5ftype_20_3e',['block_cache_write_buffer&lt; block_type &gt;',['../classstxxl_1_1hash__map_1_1block__cache__write__buffer.html',1,'stxxl::hash_map']]],
  ['block_5fmanager',['block_manager',['../classstxxl_1_1block__manager.html',1,'stxxl']]],
  ['block_5fprefetcher',['block_prefetcher',['../classstxxl_1_1block__prefetcher.html',1,'stxxl']]],
  ['block_5fscheduler',['block_scheduler',['../classstxxl_1_1block__scheduler.html',1,'stxxl']]],
  ['block_5fscheduler_5falgorithm',['block_scheduler_algorithm',['../classstxxl_1_1block__scheduler__algorithm.html',1,'stxxl']]],
  ['block_5fscheduler_5falgorithm_5foffline_5flfd',['block_scheduler_algorithm_offline_lfd',['../classstxxl_1_1block__scheduler__algorithm__offline__lfd.html',1,'stxxl']]],
  ['block_5fscheduler_5falgorithm_5foffline_5flru_5fprefetching',['block_scheduler_algorithm_offline_lru_prefetching',['../classstxxl_1_1block__scheduler__algorithm__offline__lru__prefetching.html',1,'stxxl']]],
  ['block_5fscheduler_5falgorithm_5fonline_5flru',['block_scheduler_algorithm_online_lru',['../classstxxl_1_1block__scheduler__algorithm__online__lru.html',1,'stxxl']]],
  ['block_5fscheduler_5falgorithm_5fsimulation',['block_scheduler_algorithm_simulation',['../classstxxl_1_1block__scheduler__algorithm__simulation.html',1,'stxxl']]],
  ['block_5fw_5fbids',['block_w_bids',['../classstxxl_1_1mng__local_1_1block__w__bids.html',1,'stxxl::mng_local']]],
  ['block_5fw_5fbids_3c_20type_2c_20size_2c_20rawsize_2c_200_20_3e',['block_w_bids&lt; Type, Size, RawSize, 0 &gt;',['../classstxxl_1_1mng__local_1_1block__w__bids_3_01Type_00_01Size_00_01RawSize_00_010_01_4.html',1,'stxxl::mng_local']]],
  ['block_5fw_5fbids_3c_20type_2c_28_28rawsize_2dsizeof_28bid_3c_20rawsize_20_3e_29_2anbids_29_2fsizeof_28type_29_29_2c_20rawsize_2c_20nbids_20_3e',['block_w_bids&lt; Type,((RawSize-sizeof(BID&lt; RawSize &gt;)*NBids)/sizeof(Type)), RawSize, NBids &gt;',['../classstxxl_1_1mng__local_1_1block__w__bids.html',1,'stxxl::mng_local']]],
  ['block_5fw_5fbids_3c_20type_2c_28_28rawsize_2dsizeof_28bid_3c_20rawsize_20_3e_29_2anbids_2dsizeof_28metainfotype_29_29_2fsizeof_28type_29_29_2c_20rawsize_2c_20nbids_20_3e',['block_w_bids&lt; Type,((RawSize-sizeof(BID&lt; RawSize &gt;)*NBids-sizeof(MetaInfoType))/sizeof(Type)), RawSize, NBids &gt;',['../classstxxl_1_1mng__local_1_1block__w__bids.html',1,'stxxl::mng_local']]],
  ['block_5fw_5finfo',['block_w_info',['../classstxxl_1_1mng__local_1_1block__w__info.html',1,'stxxl::mng_local']]],
  ['block_5fw_5finfo_3c_20type_2c_20rawsize_2c_20nbids_2c_20void_20_3e',['block_w_info&lt; Type, RawSize, NBids, void &gt;',['../classstxxl_1_1mng__local_1_1block__w__info_3_01Type_00_01RawSize_00_01NBids_00_01void_01_4.html',1,'stxxl::mng_local']]],
  ['block_5fw_5finfo_3c_20type_2c_20rawsize_2c_20nref_2c_20metainfotype_20_3e',['block_w_info&lt; Type, RawSize, NRef, MetaInfoType &gt;',['../classstxxl_1_1mng__local_1_1block__w__info.html',1,'stxxl::mng_local']]],
  ['blocked_5findex',['blocked_index',['../classstxxl_1_1blocked__index.html',1,'stxxl']]],
  ['btree',['btree',['../classstxxl_1_1btree_1_1btree.html',1,'stxxl::btree']]],
  ['btree_5fconst_5fiterator',['btree_const_iterator',['../classstxxl_1_1btree_1_1btree__const__iterator.html',1,'stxxl::btree']]],
  ['btree_5fiterator',['btree_iterator',['../classstxxl_1_1btree_1_1btree__iterator.html',1,'stxxl::btree']]],
  ['btree_5fiterator_3c_20self_5ftype_20_3e',['btree_iterator&lt; self_type &gt;',['../classstxxl_1_1btree_1_1btree__iterator.html',1,'stxxl::btree']]],
  ['btree_5fiterator_5fbase',['btree_iterator_base',['../classstxxl_1_1btree_1_1btree__iterator__base.html',1,'stxxl::btree']]],
  ['btree_5fiterator_5fbase_3c_20self_5ftype_20_3e',['btree_iterator_base&lt; self_type &gt;',['../classstxxl_1_1btree_1_1btree__iterator__base.html',1,'stxxl::btree']]],
  ['bucket',['bucket',['../structstxxl_1_1hash__map_1_1bucket.html',1,'stxxl::hash_map']]],
  ['buf_5fistream',['buf_istream',['../classstxxl_1_1buf__istream.html',1,'stxxl']]],
  ['buf_5fistream_5freverse',['buf_istream_reverse',['../classstxxl_1_1buf__istream__reverse.html',1,'stxxl']]],
  ['buf_5fostream',['buf_ostream',['../classstxxl_1_1buf__ostream.html',1,'stxxl']]],
  ['buffered_5freader',['buffered_reader',['../classstxxl_1_1hash__map_1_1buffered__reader.html',1,'stxxl::hash_map']]],
  ['buffered_5fwriter',['buffered_writer',['../classstxxl_1_1hash__map_1_1buffered__writer.html',1,'stxxl::hash_map']]],
  ['buffered_5fwriter',['buffered_writer',['../classstxxl_1_1buffered__writer.html',1,'stxxl']]],
  ['buffered_5fwriter_3c_20block_5ftype_20_3e',['buffered_writer&lt; block_type &gt;',['../classstxxl_1_1buffered__writer.html',1,'stxxl']]],
  ['buffered_5fwriter_3c_20stxxl_3a_3atyped_5fblock_20_3e',['buffered_writer&lt; stxxl::typed_block &gt;',['../classstxxl_1_1buffered__writer.html',1,'stxxl']]],
  ['busy_5fentry',['busy_entry',['../structstxxl_1_1write__pool_1_1busy__entry.html',1,'stxxl::write_pool']]]
];
