Stxxl: stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ > Class Template Reference
stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ > Class Template Reference
[Stream package]
Creates stream of 6-tuples from 6 input streams.
#include <stream.h>
Public Types
typedef stxxl::tuple< typename
Input1_::value_type, typename
Input2_::value_type, typename
Input3_::value_type, typename
Input4_::value_type, typename
Input5_::value_type, typename
Input6_::value_type > value_type
Standard stream typedef.
Public Member Functions
make_tuple (Input1_ &i1_, Input2_ &i2_, Input3_ &i3_, Input4_ &i4_, Input5_ &i5_, Input6_ &i6_)
Construction.
const value_type & operator* () const
Standard stream method.
const value_type * operator-> () const
make_tuple & operator++ ()
Standard stream method.
bool empty () const
Standard stream method.
Detailed Description
template<class Input1_, class Input2_, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper>
class stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >
Creates stream of 6-tuples from 6 input streams.
Template Parameters:
Input1_ type of the 1st input
Input2_ type of the 2nd input
Input3_ type of the 3rd input
Input4_ type of the 4th input
Input5_ type of the 5th input
Input6_ type of the 6th input
Member Typedef Documentation
template<class Input1_ , class Input2_ , class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> typedef stxxl::tuple< typename Input1_::value_type, typename Input2_::value_type, typename Input3_::value_type, typename Input4_::value_type, typename Input5_::value_type, typename Input6_::value_type > stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::value_type
Standard stream typedef.
Constructor & Destructor Documentation
template<class Input1_ , class Input2_ , class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::make_tuple (Input1_ & i1_, Input2_ & i2_, Input3_ & i3_, Input4_ & i4_, Input5_ & i5_, Input6_ & i6_) [inline]
Construction.
Member Function Documentation
template<class Input1_ , class Input2_ , class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> bool stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::empty () const [inline]
Standard stream method.
Referenced by stream::make_tuple< Input1_, Input2_, Stopper, Stopper, Stopper, Stopper >::make_tuple(), stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Stopper >::operator++(), stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Stopper, Stopper >::operator++(), stream::make_tuple< Input1_, Input2_, Input3_, Stopper, Stopper, Stopper >::operator++(), stream::make_tuple< Input1_, Input2_, Stopper, Stopper, Stopper, Stopper >::operator++(), and stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator++().
template<class Input1_ , class Input2_ , class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> const value_type& stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator* () const [inline]
Standard stream method.
template<class Input1_ , class Input2_ , class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> make_tuple& stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator++ () [inline]
Standard stream method.
References stream::make_tuple< Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::empty().
The documentation for this class was generated from the following file:
stream.h