Stxxl: config Class Reference
config Class Reference
[Block management layer]
Access point to disks properties.
#include <mng.h>
Inherits noncopyable.
Public Member Functions
unsigned disks_number () const
Returns number of disks available to user.
std::pair< unsigned, unsigned > regular_disk_range () const
Returns contiguous range of regular disks w/o flash devices in the array of all disks.
std::pair< unsigned, unsigned > flash_range () const
Returns contiguous range of flash devices in the array of all disks.
const std::string & disk_path (int disk) const
Returns path of disks.
stxxl::int64 disk_size (int disk) const
Returns disk size.
const std::string & disk_io_impl (int disk) const
Returns name of I/O implementation of particular disk.
Static Public Member Functions
static config * get_instance ()
Returns instance of config.
Detailed Description
Access point to disks properties.
Remarks:
is a singleton
Member Function Documentation
unsigned config::disks_number () const [inline]
Returns number of disks available to user.
Returns:
number of disks
Referenced by buf_istream< BlkTp_, BIDIteratorTp_ >::buf_istream(), stream::materialize(), and stream::runs_merger< stream::sorted_runs, Cmp_, AllocStr_ >::runs_merger().
std::pair<unsigned, unsigned> config::regular_disk_range () const [inline]
Returns contiguous range of regular disks w/o flash devices in the array of all disks.
Returns:
range [begin, end) of regular disk indices
std::pair<unsigned, unsigned> config::flash_range () const [inline]
Returns contiguous range of flash devices in the array of all disks.
Returns:
range [begin, end) of flash device indices
const std::string& config::disk_path (int disk) const [inline]
Returns path of disks.
Parameters:
disk disk's identifier
Returns:
string that contains the disk's path name
stxxl::int64 config::disk_size (int disk) const [inline]
Returns disk size.
Parameters:
disk disk's identifier
Returns:
disk size in bytes
const std::string& config::disk_io_impl (int disk) const [inline]
Returns name of I/O implementation of particular disk.
Parameters:
disk disk's identifier
config * config::get_instance () [static]
Returns instance of config.
Returns:
pointer to the instance of config
Referenced by buf_istream< BlkTp_, BIDIteratorTp_ >::buf_istream(), stream::materialize(), stream::runs_merger< stream::sorted_runs, Cmp_, AllocStr_ >::runs_merger(), and vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::vector().
The documentation for this class was generated from the following files:
mng.h
mng.cpp