Stxxl: request_ptr Class Reference
request_ptr Class Reference
[I/O primitives layer]
A smart wrapper for request pointer.
#include <iobase.h>
Public Member Functions
request_ptr (request *ptr_=NULL)
Constructs an request_ptr from request pointer.
request_ptr (const request_ptr &p)
Constructs an request_ptr from a request_ptr object.
~request_ptr ()
Destructor.
request_ptr & operator= (const request_ptr &p)
Assignment operator from request_ptr object.
request_ptr & operator= (request *p)
Assignment operator from request pointer.
request & operator* () const
"Star" operator
request * operator-> () const
"Arrow" operator
request * get () const
Access to owned request object (synonym for operator->()).
bool valid () const
Returns true if object is initialized.
bool empty () const
Returns true if object is not initialized.
Detailed Description
A smart wrapper for request pointer.
Implemented as reference counting smart pointer.
Constructor & Destructor Documentation
request_ptr::request_ptr (request * ptr_ = NULL) [inline]
Constructs an request_ptr from request pointer.
request_ptr::request_ptr (const request_ptr & p) [inline]
Constructs an request_ptr from a request_ptr object.
request_ptr::~request_ptr () [inline]
Destructor.
Member Function Documentation
request_ptr& request_ptr::operator= (const request_ptr & p) [inline]
Assignment operator from request_ptr object.
Returns:
reference to itself
References ptr.
request_ptr& request_ptr::operator= (request * p) [inline]
Assignment operator from request pointer.
Returns:
reference to itself
request& request_ptr::operator* () const [inline]
"Star" operator
Returns:
reference to owned request object
request* request_ptr::operator-> () const [inline]
"Arrow" operator
Returns:
pointer to owned request object
request* request_ptr::get () const [inline]
Access to owned request object (synonym for operator->()).
Returns:
reference to owned request object
Warning:
Creation another request_ptr from the returned request or deletion causes unpredictable behaviour. Do not do that!
Referenced by syscall_file::aread(), sim_disk_file::aread(), mmap_file::aread(), syscall_file::awrite(), sim_disk_file::awrite(), and mmap_file::awrite().
bool request_ptr::valid () const [inline]
Returns true if object is initialized.
bool request_ptr::empty () const [inline]
Returns true if object is not initialized.
The documentation for this class was generated from the following file:
iobase.h