Stxxl: disk_queues Class Reference
disk_queues Class Reference
[I/O primitives layer]
Encapsulates disk queues.
#include <iobase.h>
Inherits noncopyable.
Public Member Functions
void set_priority_op (disk_queue::priority_op op)
Changes requests priorities.
Detailed Description
Encapsulates disk queues.
Remarks:
is a singleton
Member Function Documentation
void disk_queues::set_priority_op (disk_queue::priority_op op) [inline]
Changes requests priorities.
Parameters:
op one of:
READ, read requests are served before write requests within a disk queue
WRITE, write requests are served before read requests within a disk queue
NONE, read and write requests are served by turns, alternately
Referenced by buffered_writer< BlkTp_ >::buffered_writer(), stream::runs_creator< use_push< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::push(), and stream::runs_merger< stream::sorted_runs, Cmp_, AllocStr_ >::runs_merger().
The documentation for this class was generated from the following files:
iobase.h
diskqueue.cpp