Stxxl: ufs_file_base Class Reference
ufs_file_base Class Reference
[File implementations]
Base for UNIX file system implementations.
#include <ufs_file.h>
Public Member Functions
stxxl::int64 size ()
Returns size of the file.
void set_size (stxxl::int64 newsize)
Changes the size of the file.
void lock ()
Locks file for reading and writing.
Detailed Description
Base for UNIX file system implementations.
Member Function Documentation
stxxl::int64 ufs_file_base::size () [virtual]
Returns size of the file.
Returns:
file size in bytes
Implements file.
Referenced by set_size(), and sim_disk_file::set_size().
void ufs_file_base::set_size (stxxl::int64 newsize) [virtual]
Changes the size of the file.
Parameters:
newsize value of the new file size
Implements file.
Reimplemented in sim_disk_file.
References size().
void ufs_file_base::lock () [virtual]
Locks file for reading and writing.
Reimplemented from file.
The documentation for this class was generated from the following files:
ufs_file.h
ufs_file.cpp