Stxxl: mem_request Class Reference
mem_request Class Reference
[File implementations]
Implementation of request based on memcpy().
#include <mem_file.h>
Public Member Functions
void wait ()
Suspends calling thread until completion of the request.
bool poll ()
Polls the status of the request.
const char * io_type ()
Identifies the type of request I/O implementation.
Detailed Description
Implementation of request based on memcpy().
Member Function Documentation
const char * mem_request::io_type () [virtual]
Identifies the type of request I/O implementation.
Returns:
pointer to null terminated string of characters, containing the name of I/O implementation
Reimplemented from request.
bool mem_request::poll () [virtual]
Polls the status of the request.
Returns:
true if request is completed, otherwise false
Implements request.
References request::check_errors(), and wait().
void mem_request::wait () [virtual]
Suspends calling thread until completion of the request.
Implements request.
References request::check_errors().
Referenced by poll().
The documentation for this class was generated from the following files:
mem_file.h
mem_file.cpp