Stxxl: ufs_request_base Class Reference
ufs_request_base Class Reference
[File implementations]
Base for UNIX file system implementations.
#include <ufs_file.h>
Public Member Functions
void wait ()
Suspends calling thread until completion of the request.
bool poll ()
Polls the status of the request.
const char * io_type ()
Identifies the type of request I/O implementation.
Detailed Description
Base for UNIX file system implementations.
Member Function Documentation
const char * ufs_request_base::io_type () [virtual]
Identifies the type of request I/O implementation.
Returns:
pointer to null terminated string of characters, containing the name of I/O implementation
Reimplemented from request.
Reimplemented in mmap_request, sim_disk_request, and syscall_request.
bool ufs_request_base::poll () [virtual]
Polls the status of the request.
Returns:
true if request is completed, otherwise false
Implements request.
References request::check_errors(), and wait().
void ufs_request_base::wait () [virtual]
Suspends calling thread until completion of the request.
Implements request.
References request::check_errors().
Referenced by poll().
The documentation for this class was generated from the following files:
ufs_file.h
ufs_file.cpp