Stxxl: stream::runs_merger< RunsType_, Cmp_, AllocStr_ > Class Template Reference
stream::runs_merger< RunsType_, Cmp_, AllocStr_ > Class Template Reference
[Stream package]
Merges sorted runs.
#include <sort_stream.h>
Public Types
typedef
sorted_runs_type::value_type value_type
Standard stream typedef.
Public Member Functions
runs_merger (const sorted_runs_type &r, value_cmp c, unsigned_type memory_to_use)
Creates a runs merger object.
bool empty () const
Standard stream method.
runs_merger & operator++ ()
Standard stream method.
const value_type & operator* () const
Standard stream method.
const value_type * operator-> () const
Standard stream method.
virtual ~runs_merger ()
Destructor.
Detailed Description
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY>
class stream::runs_merger< RunsType_, Cmp_, AllocStr_ >
Merges sorted runs.
Template parameters:
RunsType_ type of the sorted runs, available as runs_creator::sorted_runs_type ,
Cmp_ type of comparison object used for merging
AllocStr_ allocation strategy used to allocate the blocks for storing intermediate results if several merge passes are required
Member Typedef Documentation
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> typedef sorted_runs_type::value_type stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::value_type
Standard stream typedef.
Constructor & Destructor Documentation
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::runs_merger (const sorted_runs_type & r, value_cmp c, unsigned_type memory_to_use) [inline]
Creates a runs merger object.
Parameters:
r input sorted runs object
c comparison object
memory_to_use amount of memory available for the merger in bytes
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> virtual stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::~runs_merger () [inline, virtual]
Destructor.
Remarks:
Deallocates blocks of the input sorted runs object
Member Function Documentation
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> bool stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::empty () const [inline]
Standard stream method.
Referenced by stream::runs_merger< sorted_runs_type, Cmp_, AllocStr_ >::operator*(), stream::runs_merger< sorted_runs_type, Cmp_, AllocStr_ >::operator++(), stream::runs_merger< sorted_runs_type, Cmp_, AllocStr_ >::operator->(), and stream::runs_merger< sorted_runs_type, Cmp_, AllocStr_ >::runs_merger().
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> const value_type& stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::operator* () const [inline]
Standard stream method.
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> runs_merger& stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::operator++ () [inline]
Standard stream method.
template<class RunsType_, class Cmp_, class AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY> const value_type* stream::runs_merger< RunsType_, Cmp_, AllocStr_ >::operator-> () const [inline]
Standard stream method.
The documentation for this class was generated from the following file:
sort_stream.h