Stxxl: element_block< T, Size_ > Class Template Reference
element_block< T, Size_ > Class Template Reference
Contains data elements for stxxl::typed_block , not intended for direct use.
#include <typed_block.h>
Public Types
enum { size = Size_ }
typedef T type
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef type * pointer
typedef pointer iterator
typedef const type * const_iterator
Public Member Functions
reference operator[] (int i)
An operator to access elements in the block.
iterator begin ()
Returns iterator pointing to the first element.
const_iterator begin () const
Returns const_iterator pointing to the first element.
const_iterator cbegin () const
Returns const_iterator pointing to the first element.
iterator end ()
Returns iterator pointing to the end element.
const_iterator end () const
Returns const_iterator pointing to the end element.
const_iterator cend () const
Returns const_iterator pointing to the end element.
Public Attributes
T elem [size]
Array of elements of type T.
Detailed Description
template<class T, unsigned Size_>
class element_block< T, Size_ >
Contains data elements for stxxl::typed_block , not intended for direct use.
Member Enumeration Documentation
template<class T, unsigned Size_> anonymous enum
Enumerator:
size
number of elements in the block
Member Function Documentation
template<class T, unsigned Size_> iterator element_block< T, Size_ >::begin () [inline]
Returns iterator pointing to the first element.
Referenced by element_block< T_, Size_ >::cbegin(), and stream::runs_creator< use_push< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::push().
template<class T, unsigned Size_> const_iterator element_block< T, Size_ >::begin () const [inline]
Returns const_iterator pointing to the first element.
template<class T, unsigned Size_> const_iterator element_block< T, Size_ >::cbegin () const [inline]
Returns const_iterator pointing to the first element.
template<class T, unsigned Size_> const_iterator element_block< T, Size_ >::cend () const [inline]
Returns const_iterator pointing to the end element.
template<class T, unsigned Size_> const_iterator element_block< T, Size_ >::end () const [inline]
Returns const_iterator pointing to the end element.
template<class T, unsigned Size_> iterator element_block< T, Size_ >::end () [inline]
Returns iterator pointing to the end element.
Referenced by element_block< T_, Size_ >::cend(), and stream::runs_creator< use_push< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::push().
template<class T, unsigned Size_> reference element_block< T, Size_ >::operator[] (int i) [inline]
An operator to access elements in the block.
Member Data Documentation
template<class T, unsigned Size_> T element_block< T, Size_ >::elem[size]
Array of elements of type T.
Referenced by element_block< T_, Size_ >::begin(), element_block< T_, Size_ >::end(), element_block< T_, Size_ >::operator[](), queue< ValTp, BlkSz, AllocStr, SzTp >::pop(), and queue< ValTp, BlkSz, AllocStr, SzTp >::push().
The documentation for this class was generated from the following file:
typed_block.h