Stxxl: request_state_impl_basic Class Reference
request_state_impl_basic Class Reference
[File implementations]
Basic state implemenatition for most request implementations.
#include <request_state_impl_basic.h>
Public Member Functions
void wait (bool measure_time=true)
Suspends calling thread until completion of the request.
bool poll ()
Polls the status of the request.
bool cancel ()
Cancel request The request is cancelled unless already being processed. However, cancellation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
Protected Types
enum request_state { OP = 0, DONE = 1, READY2DIE = 2 }
Protected Member Functions
request_state_impl_basic (const completion_handler &on_cmpl, file *f, void *buf, offset_type off, size_type b, request_type t)
Protected Attributes
state< request_state > _state
Detailed Description
Basic state implemenatition for most request implementations.
Member Enumeration Documentation
enum request_state_impl_basic::request_state [protected]
states of request OP - operating, DONE - request served, READY2DIE - can be destroyed
Member Function Documentation
bool request_state_impl_basic::cancel () [virtual]
Cancel request The request is cancelled unless already being processed. However, cancellation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
Returns:
true iff the request was cancelled successfully
Implements request_base.
References file::get_queue_id().
bool request_state_impl_basic::poll () [virtual]
Polls the status of the request.
Returns:
true if request is completed, otherwise false
Implements request_base.
References request::check_errors().
void request_state_impl_basic::wait (bool measure_time = true) [virtual]
Suspends calling thread until completion of the request.
Implements request_base.
References request::check_errors().
The documentation for this class was generated from the following files:
request_state_impl_basic.h
request_state_impl_basic.cpp