STXXL: stxxl::request_queue_impl_qwqr Class Reference
stxxl::request_queue_impl_qwqr Class Reference
I/O Primitives Layer
Detailed Description
Definition at line 30 of file request_queue_impl_qwqr.h.
Public Member Functions
request_queue_impl_qwqr (int n=1)
~request_queue_impl_qwqr ()
void add_request (request_ptr &req)
bool cancel_request (request_ptr &req)
void set_priority_op (priority_op op)
Public Member Functions inherited from stxxl::request_queue
virtual ~request_queue ()
Private Types
typedef std::list< request_ptr > queue_type
typedef request_queue_impl_qwqr self
Static Private Member Functions
static void * worker (void *arg)
Private Attributes
state< thread_state > m_thread_state
mutex read_mutex
queue_type read_queue
semaphore sem
thread_type thread
mutex write_mutex
queue_type write_queue
Static Private Attributes
static const priority_op _priority_op = WRITE
Additional Inherited Members
Public Types inherited from stxxl::request_queue
enum priority_op { READ, WRITE, NONE }
Protected Types inherited from stxxl::request_queue_impl_worker
enum thread_state { NOT_RUNNING, RUNNING, TERMINATING, TERMINATED }
typedef pthread_t thread_type
Protected Member Functions inherited from stxxl::request_queue_impl_worker
void start_thread (void *(*worker)(void *), void *arg, thread_type &t, state< thread_state > &s)
void stop_thread (thread_type &t, state< thread_state > &s, semaphore &sem)
Member Typedef Documentation
typedef std::list<request_ptr> stxxl::request_queue_impl_qwqr::queue_type private
Definition at line 34 of file request_queue_impl_qwqr.h.
typedef request_queue_impl_qwqr stxxl::request_queue_impl_qwqr::self private
Definition at line 33 of file request_queue_impl_qwqr.h.
Constructor & Destructor Documentation
stxxl::request_queue_impl_qwqr::request_queue_impl_qwqr (int n = 1)
Definition at line 45 of file request_queue_impl_qwqr.cpp.
References m_thread_state, stxxl::request_queue_impl_worker::start_thread(), stxxl::STXXL_UNUSED(), thread, and worker().
stxxl::request_queue_impl_qwqr::~request_queue_impl_qwqr ()
Definition at line 129 of file request_queue_impl_qwqr.cpp.
References m_thread_state, sem, stxxl::request_queue_impl_worker::stop_thread(), and thread.
Member Function Documentation
void stxxl::request_queue_impl_qwqr::add_request (request_ptr & req) virtual
Implements stxxl::request_queue.
Definition at line 52 of file request_queue_impl_qwqr.cpp.
References _STXXL_FORCE_SEQUENTIAL, stxxl::counting_ptr< Type >::empty(), stxxl::counting_ptr< Type >::get(), stxxl::request::get_type(), m_thread_state, stxxl::request_interface::READ, read_mutex, read_queue, stxxl::request_queue_impl_worker::RUNNING, sem, STXXL_ERRMSG, STXXL_THROW_INVALID_ARGUMENT, write_mutex, and write_queue.
bool stxxl::request_queue_impl_qwqr::cancel_request (request_ptr & req) virtual
Implements stxxl::request_queue.
Definition at line 95 of file request_queue_impl_qwqr.cpp.
References _STXXL_FORCE_SEQUENTIAL, stxxl::counting_ptr< Type >::empty(), stxxl::find(), stxxl::counting_ptr< Type >::get(), stxxl::request::get_type(), m_thread_state, stxxl::request_interface::READ, read_mutex, read_queue, stxxl::request_queue_impl_worker::RUNNING, sem, STXXL_THROW_INVALID_ARGUMENT, write_mutex, and write_queue.
void stxxl::request_queue_impl_qwqr::set_priority_op (priority_op op) inline virtual
Reimplemented from stxxl::request_queue.
Definition at line 57 of file request_queue_impl_qwqr.h.
References stxxl::STXXL_UNUSED().
void * stxxl::request_queue_impl_qwqr::worker (void * arg) static private
Definition at line 134 of file request_queue_impl_qwqr.cpp.
References stxxl::request_queue::NONE, stxxl::request_queue::READ, sem, stxxl::request_interface::serve(), STXXL_VERBOSE2, stxxl::request_queue_impl_worker::TERMINATED, stxxl::request_queue_impl_worker::TERMINATING, stxxl::scoped_mutex_lock::unlock(), and stxxl::request_queue::WRITE.
Referenced by request_queue_impl_qwqr().
Member Data Documentation
const priority_op stxxl::request_queue_impl_qwqr::_priority_op = WRITE static private
Definition at line 45 of file request_queue_impl_qwqr.h.
state<thread_state> stxxl::request_queue_impl_qwqr::m_thread_state private
Definition at line 41 of file request_queue_impl_qwqr.h.
Referenced by add_request(), cancel_request(), request_queue_impl_qwqr(), and ~request_queue_impl_qwqr().
mutex stxxl::request_queue_impl_qwqr::read_mutex private
Definition at line 37 of file request_queue_impl_qwqr.h.
Referenced by add_request(), and cancel_request().
queue_type stxxl::request_queue_impl_qwqr::read_queue private
Definition at line 39 of file request_queue_impl_qwqr.h.
Referenced by add_request(), and cancel_request().
semaphore stxxl::request_queue_impl_qwqr::sem private
Definition at line 43 of file request_queue_impl_qwqr.h.
Referenced by add_request(), cancel_request(), worker(), and ~request_queue_impl_qwqr().
thread_type stxxl::request_queue_impl_qwqr::thread private
Definition at line 42 of file request_queue_impl_qwqr.h.
Referenced by request_queue_impl_qwqr(), and ~request_queue_impl_qwqr().
mutex stxxl::request_queue_impl_qwqr::write_mutex private
Definition at line 36 of file request_queue_impl_qwqr.h.
Referenced by add_request(), and cancel_request().
queue_type stxxl::request_queue_impl_qwqr::write_queue private
Definition at line 38 of file request_queue_impl_qwqr.h.
Referenced by add_request(), and cancel_request().
The documentation for this class was generated from the following files:
include/stxxl/bits/io/request_queue_impl_qwqr.h
lib/io/request_queue_impl_qwqr.cpp