STXXL: stxxl::priority_queue_local Namespace Reference
stxxl::priority_queue_local Namespace Reference
internals
Classes
struct compute_N
struct compute_N< 1, X_, CriticalSize_ >
struct dummy
class ext_merger
External merger, based on the loser tree data structure.
struct find_B_m
struct find_B_m< E_, IntMem, MaxItems, 2048, 1, stop >
struct find_B_m< E_, IntMem, MaxItems, B_, m_, true >
struct find_settings
class internal_bounded_stack
Similar to std::stack, with the following differences:
class internal_priority_queue
Similar to std::priority_queue, with the following differences:
class invert_order
Inverts the order of a comparison functor by swapping its arguments.
class loser_tree
Loser tree from Knuth, "Sorting and Searching", Section 5.4.1.
struct Parameters_for_priority_queue_not_found_Increase_IntMem
struct Parameters_not_found_Try_to_change_the_Tune_parameter
class short_sequence
Functions
template<class InputIterator , class OutputIterator , class CompareType >
void merge3_iterator (InputIterator &source0, InputIterator &source1, InputIterator &source2, OutputIterator target, unsigned_type length, CompareType &cmp)
template<class InputIterator , class OutputIterator , class CompareType >
void merge4_iterator (InputIterator &source0, InputIterator &source1, InputIterator &source2, InputIterator &source3, OutputIterator target, unsigned_type length, CompareType &cmp)
template<class InputIterator , class OutputIterator , class CompareType >
void merge_iterator (InputIterator &source0, InputIterator &source1, OutputIterator target, unsigned_type length, CompareType &cmp)
Detailed Description
Function Documentation
template<class InputIterator , class OutputIterator , class CompareType > void stxxl::priority_queue_local::merge3_iterator (InputIterator & source0, InputIterator & source1, InputIterator & source2, OutputIterator target, unsigned_type length, CompareType & cmp)
Definition at line 73 of file pq_mergers.h.
References Merge3Case.
Referenced by stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< ConfigType >::refill_delete_buffer().
template<class InputIterator , class OutputIterator , class CompareType > void stxxl::priority_queue_local::merge4_iterator (InputIterator & source0, InputIterator & source1, InputIterator & source2, InputIterator & source3, OutputIterator target, unsigned_type length, CompareType & cmp)
Definition at line 141 of file pq_mergers.h.
References Merge4Case, and StartMerge4.
Referenced by stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< ConfigType >::refill_delete_buffer().
template<class InputIterator , class OutputIterator , class CompareType > void stxxl::priority_queue_local::merge_iterator (InputIterator & source0, InputIterator & source1, OutputIterator target, unsigned_type length, CompareType & cmp)
Definition at line 41 of file pq_mergers.h.
Referenced by stxxl::priority_queue< ConfigType >::empty_insert_heap(), stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< ConfigType >::refill_delete_buffer().