STXXL: stxxl::sort_helper Namespace Reference
stxxl::sort_helper Namespace Reference
Classes
struct run_cursor2_cmp
struct trigger_entry
struct trigger_entry_cmp
Functions
template<typename SequenceVector , typename ValueType , typename Comparator >
unsigned_type count_elements_less_equal (const SequenceVector &seqs, const ValueType &bound, Comparator cmp)
template<typename SequenceVector , typename BufferPtrVector , typename Prefetcher >
void refill_or_remove_empty_sequences (SequenceVector &seqs, BufferPtrVector &buffers, Prefetcher &prefetcher)
template<typename StrictWeakOrdering >
void verify_sentinel_strict_weak_ordering (StrictWeakOrdering cmp)
Detailed Description
Function Documentation
template<typename SequenceVector , typename ValueType , typename Comparator > unsigned_type stxxl::sort_helper::count_elements_less_equal (const SequenceVector & seqs, const ValueType & bound, Comparator cmp) inline
Definition at line 93 of file sort_helper.h.
References stxxl::count(), and STXXL_VERBOSE1.
Referenced by stxxl::stream::basic_runs_merger< sorted_runs_type, CompareType_, AllocStr_ >::fill_buffer_block(), and stxxl::sort_local::merge_runs().
template<typename SequenceVector , typename BufferPtrVector , typename Prefetcher > void stxxl::sort_helper::refill_or_remove_empty_sequences (SequenceVector & seqs, BufferPtrVector & buffers, Prefetcher & prefetcher) inline
Definition at line 112 of file sort_helper.h.
References STXXL_VERBOSE1.
Referenced by stxxl::stream::basic_runs_merger< sorted_runs_type, CompareType_, AllocStr_ >::fill_buffer_block(), and stxxl::sort_local::merge_runs().
template<typename StrictWeakOrdering > void stxxl::sort_helper::verify_sentinel_strict_weak_ordering (StrictWeakOrdering cmp) inline
Definition at line 29 of file sort_helper.h.
References stxxl::STXXL_UNUSED().
Referenced by stxxl::stream::basic_runs_creator< stream::use_push< ValueType >, cmp_type, BlockSize_, alloc_strategy_type >::basic_runs_creator(), stxxl::stream::basic_runs_merger< sorted_runs_type, CompareType_, AllocStr_ >::basic_runs_merger(), stxxl::stream::check_sorted_runs(), stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::runs_creator(), stxxl::stream::runs_creator< from_sorted_sequences< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::runs_creator(), stxxl::sort(), and stxxl::stream::sort< Input_, CompareType_, BlockSize_, AllocStr_, runs_creator_type >::sort().