STXXL: stxxl::ksort_local Namespace Reference
stxxl::ksort_local Namespace Reference
Algorithms
Classes
class key_comparison
struct run_cursor2_cmp
struct trigger_entry
struct type_key
struct write_completion_handler
Functions
template<typename block_type , typename run_type , typename key_ext_ >
bool check_ksorted_runs (run_type **runs, unsigned_type nruns, unsigned_type m, key_ext_ keyext)
template<typename block_type , typename run_type , typename input_bid_iterator , typename key_extractor >
void create_runs (input_bid_iterator it, run_type **runs, const unsigned_type nruns, const unsigned_type m2, key_extractor keyobj)
template<typename block_type , typename alloc_strategy , typename input_bid_iterator , typename key_extractor >
simple_vector< trigger_entry
< typename
block_type::bid_type, typename
key_extractor::key_type > > * ksort_blocks (input_bid_iterator input_bids, unsigned_type _n, unsigned_type _m, key_extractor keyobj)
template<typename block_type , typename run_type , typename key_extractor >
void merge_runs (run_type **in_runs, unsigned_type nruns, run_type *out_run, unsigned_type _m, key_extractor keyobj)
template<typename BIDType , typename KeyType >
bool operator< (const trigger_entry< BIDType, KeyType > &a, const trigger_entry< BIDType, KeyType > &b)
template<typename type , typename key1 >
bool operator< (const type_key< type, key1 > &a, const type_key< type, key1 > &b)
template<typename BIDType , typename KeyType >
bool operator> (const trigger_entry< BIDType, KeyType > &a, const trigger_entry< BIDType, KeyType > &b)
template<typename type , typename key1 >
bool operator> (const type_key< type, key1 > &a, const type_key< type, key1 > &b)
template<typename type_key_ , typename block_type , typename run_type , typename input_bid_iterator , typename key_extractor >
void write_out (type_key_ *begin, type_key_ *end, block_type *&cur_blk, const block_type *end_blk, int_type &out_block, int_type &out_pos, run_type &run, write_completion_handler< block_type, typename block_type::bid_type > *&next_read, typename block_type::bid_type *&bids, request_ptr *write_reqs, request_ptr *read_reqs, input_bid_iterator &it, key_extractor keyobj)
Detailed Description
Function Documentation
template<typename block_type , typename run_type , typename key_ext_ > bool stxxl::ksort_local::check_ksorted_runs (run_type ** runs, unsigned_type nruns, unsigned_type m, key_ext_ keyext)
Definition at line 347 of file ksort.h.
References stxxl::is_sorted(), stxxl::make_element_iterator(), stxxl::STXXL_MIN(), STXXL_MSG, and stxxl::wait_all().
template<typename block_type , typename run_type , typename input_bid_iterator , typename key_extractor > void stxxl::ksort_local::create_runs (input_bid_iterator it, run_type ** runs, const unsigned_type nruns, const unsigned_type m2, key_extractor keyobj)
Definition at line 185 of file ksort.h.
References stxxl::classify(), stxxl::classify_block(), stxxl::block_manager::delete_block(), stxxl::exclusive_prefix_sum(), stxxl::ilog2_ceil(), stxxl::ilog2_floor(), stxxl::l1sort(), STXXL_L2_SIZE, STXXL_VERBOSE, stxxl::request_interface::wait(), stxxl::wait_all(), and write_out().
Referenced by ksort_blocks(), and stxxl::sort_local::sort_blocks().
template<typename block_type , typename alloc_strategy , typename input_bid_iterator , typename key_extractor > simple_vector<trigger_entry<typename block_type::bid_type, typename key_extractor::key_type> >* stxxl::ksort_local::ksort_blocks (input_bid_iterator input_bids, unsigned_type _n, unsigned_type _m, key_extractor keyobj)
Definition at line 538 of file ksort.h.
References create_runs(), stxxl::div_ceil(), stxxl::make_bid_iterator(), stxxl::block_manager::new_block(), stxxl::block_manager::new_blocks(), stxxl::optimal_merge_factor(), stxxl::STXXL_MIN(), stxxl::STXXL_UNUSED(), STXXL_VERBOSE, and stxxl::timestamp().
Referenced by stxxl::ksort().
template<typename block_type , typename run_type , typename key_extractor > void stxxl::ksort_local::merge_runs (run_type ** in_runs, unsigned_type nruns, run_type * out_run, unsigned_type _m, key_extractor keyobj)
Definition at line 446 of file ksort.h.
References _STXXL_SORT_TRIGGER_FORCE_SEQUENTIAL, stxxl::compute_prefetch_schedule(), stxxl::block_manager::delete_block(), stxxl::STXXL_MAX(), and STXXL_VERBOSE.
template<typename BIDType , typename KeyType > bool stxxl::ksort_local::operator< (const trigger_entry< BIDType, KeyType > & a, const trigger_entry< BIDType, KeyType > & b) inline
Definition at line 72 of file ksort.h.
template<typename type , typename key1 > bool stxxl::ksort_local::operator< (const type_key< type, key1 > & a, const type_key< type, key1 > & b)
Definition at line 98 of file ksort.h.
References stxxl::ksort_local::type_key< type, key_type1 >::key.
template<typename BIDType , typename KeyType > bool stxxl::ksort_local::operator> (const trigger_entry< BIDType, KeyType > & a, const trigger_entry< BIDType, KeyType > & b) inline
Definition at line 79 of file ksort.h.
References stxxl::ksort_local::trigger_entry< BIDType, KeyType >::key.
template<typename type , typename key1 > bool stxxl::ksort_local::operator> (const type_key< type, key1 > & a, const type_key< type, key1 > & b)
Definition at line 104 of file ksort.h.
References stxxl::ksort_local::type_key< type, key_type1 >::key.
template<typename type_key_ , typename block_type , typename run_type , typename input_bid_iterator , typename key_extractor > void stxxl::ksort_local::write_out (type_key_ * begin, type_key_ * end, block_type *& cur_blk, const block_type * end_blk, int_type & out_block, int_type & out_pos, run_type & run, write_completion_handler< block_type, typename block_type::bid_type > *& next_read, typename block_type::bid_type *& bids, request_ptr * write_reqs, request_ptr * read_reqs, input_bid_iterator & it, key_extractor keyobj) inline
Definition at line 127 of file ksort.h.
References stxxl::ksort_local::write_completion_handler< block_type, bid_type >::bid, stxxl::ksort_local::write_completion_handler< block_type, bid_type >::block, and stxxl::ksort_local::write_completion_handler< block_type, bid_type >::req.
Referenced by create_runs().