Stxxl: stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ > Class Template Reference
stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ > Class Template Reference
[Stream package]
Forms sorted runs of data taking elements in sorted order (element by element).
#include <sort_stream.h>
Public Member Functions
runs_creator (Cmp_ c, unsigned_type memory_to_use)
Creates the object.
void push (const value_type &val)
Adds new element to the current run.
void finish ()
Finishes current run and begins new one.
const sorted_runs_type & result ()
Returns the sorted runs object.
Detailed Description
template<class ValueType_, class Cmp_, unsigned BlockSize_, class AllocStr_>
class stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >
Forms sorted runs of data taking elements in sorted order (element by element).
A specialization of runs_creator that allows to create sorted runs data structure usable for runs_merger from sequences of elements in sorted order.
Template parameters:
ValueType_ type of values (parameter for from_sorted_sequences strategy)
Cmp_ type of comparison object used for sorting the runs
BlockSize_ size of blocks used to store the runs
AllocStr_ functor that defines allocation strategy for the runs
Constructor & Destructor Documentation
template<class ValueType_, class Cmp_, unsigned BlockSize_, class AllocStr_> stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::runs_creator (Cmp_ c, unsigned_type memory_to_use) [inline]
Creates the object.
Parameters:
c comparator object
memory_to_use memory amount that is allowed to used by the sorter in bytes. Recommended value: 2 * block_size * D
Member Function Documentation
template<class ValueType_, class Cmp_, unsigned BlockSize_, class AllocStr_> void stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::push (const value_type & val) [inline]
Adds new element to the current run.
Parameters:
val value to be added to the current run
References block_manager::get_instance(), and block_manager::new_blocks().
template<class ValueType_, class Cmp_, unsigned BlockSize_, class AllocStr_> void stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::finish () [inline]
Finishes current run and begins new one.
References block_manager::get_instance(), and block_manager::new_blocks().
template<class ValueType_, class Cmp_, unsigned BlockSize_, class AllocStr_> const sorted_runs_type& stream::runs_creator< from_sorted_sequences< ValueType_ >, Cmp_, BlockSize_, AllocStr_ >::result () [inline]
Returns the sorted runs object.
Returns:
Sorted runs object
Remarks:
Returned object is intended to be used by runs_merger object as input
The documentation for this class was generated from the following file:
sort_stream.h