Stxxl: vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > Class Template Reference
vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > Class Template Reference
[Internals]
External vector container.
#include <vector.h>
Public Member Functions
vector (file *from)
Construct vector from a file.
Detailed Description
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE (Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64>
class vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >
External vector container.
For semantics of the methods see documentation of the STL std::vector Template parameters:
Tp_ type of contained objects
PgSz_ number of blocks in a page
PgTp_ pager type, random_pager<x> or lru_pager<x>, where x is number of pages, default is lru_pager<8>
BlkSize_ external block size in bytes, default is 2 Mbytes
AllocStr_ one of allocation strategies: striping , RC , SR , or FR default is RC
Memory consumption: BlkSize_*x*PgSz_ bytes
Warning:
Do not store references to the elements of an external vector. Such references might be invalidated during any following access to elements of the vector
Constructor & Destructor Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE (Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::vector (file * from) [inline]
Construct vector from a file.
Parameters:
from file to be constructed from
Warning:
Only one vector can be assigned to a file (does not matter whether the files are different file objects). The block size of the vector must me a multiple of the element size sizeof(Tp_) and the page size (4096).
References file::get_disk_number(), config::get_instance(), block_manager::get_instance(), typed_block< RawSize_, T_, NRef_, InfoType_ >::raw_size, and file::set_size().
The documentation for this class was generated from the following file:
vector.h