Stxxl: File implementations
File implementations
[I/O primitives layer]
Classes
class mmap_file
Implementation of memory mapped access file.
class mmap_request
Implementation of memory mapped access file request.
class sim_disk_file
Implementation of disk emulation.
class sim_disk_request
Implementation of disk emulation.
class syscall_file
Implementation of file based on UNIX syscalls.
class syscall_request
Implementation of request based on UNIX syscalls.
class ufs_file_base
Base for UNIX file system implementations.
class ufs_request_base
Base for UNIX file system implementations.
Functions
stxxl::int64 ufs_file_base::size ()
Returns size of the file.
void ufs_file_base::set_size (stxxl::int64 newsize)
Changes the size of the file.
void ufs_file_base::lock ()
Locks file for reading and writing.
void ufs_request_base::wait ()
Suspends calling thread until completion of the request.
bool ufs_request_base::poll ()
Polls the status of the request.
const char * ufs_request_base::io_type ()
Identifies the type of request I/O implementation.
Detailed Description
Implemantations of stxxl::file and stxxl::request for various file access methods
Function Documentation
const char * ufs_request_base::io_type () [virtual, inherited]
Identifies the type of request I/O implementation.
Returns:
pointer to null terminated string of characters, containing the name of I/O implementation
Reimplemented from request.
Reimplemented in mmap_request, sim_disk_request, and syscall_request.
void ufs_file_base::lock () [virtual, inherited]
Locks file for reading and writing.
Reimplemented from file.
bool ufs_request_base::poll () [virtual, inherited]
Polls the status of the request.
Returns:
true if request is comleted, otherwise false
Implements request.
References request::check_errors(), and ufs_request_base::wait().
void ufs_file_base::set_size (stxxl::int64 newsize) [virtual, inherited]
Changes the size of the file.
Parameters:
newsize value of the new file size
Implements file.
Reimplemented in sim_disk_file.
References ufs_file_base::size().
stxxl::int64 ufs_file_base::size () [virtual, inherited]
Returns size of the file.
Returns:
file size in bytes
Implements file.
Referenced by ufs_file_base::set_size(), and sim_disk_file::set_size().
void ufs_request_base::wait () [virtual, inherited]
Suspends calling thread until completion of the request.
Implements request.
References request::check_errors().
Referenced by ufs_request_base::poll().