STXXL: std::numeric_limits< stxxl::uint_pair< HighType > > Class Template Reference
std::numeric_limits< stxxl::uint_pair< HighType > > Class Template Reference
Detailed Description
template<typename HighType>
class std::numeric_limits< stxxl::uint_pair< HighType > >
template class providing some numeric_limits fields for uint_pair types.
Definition at line 264 of file uint_types.h.
Static Public Member Functions
static const stxxl::uint_pair
< HighType > epsilon ()
epsilon is zero
static stxxl::uint_pair< HighType > lowest ()
return an uint_pair instance containing the smallest value possible
static stxxl::uint_pair< HighType > max ()
return an uint_pair instance containing the largest value possible
static stxxl::uint_pair< HighType > min ()
return an uint_pair instance containing the smallest value possible
static const stxxl::uint_pair
< HighType > round_error ()
rounding error is zero
Static Public Attributes
static const int digits = stxxl::uint_pair<HighType>::digits
number of binary digits (bits) in uint_pair
static const bool has_infinity = false
no infinity
static const bool is_exact = true
unit_pair types contain exact integers
static const bool is_integer = true
uint_pair types are integers
static const bool is_signed = false
unit_pair types are unsigned
static const bool is_specialized = true
yes we have information about uint_pair
static const int max_exponent = 0
no exponent
static const int max_exponent10 = 0
no exponent
static const int min_exponent = 0
no exponent
static const int min_exponent10 = 0
no exponent
static const int radix = 2
unit_pair radix is binary
Member Function Documentation
template<typename HighType > static const stxxl::uint_pair<HighType> std::numeric_limits< stxxl::uint_pair< HighType > >::epsilon () inline static
epsilon is zero
Definition at line 298 of file uint_types.h.
template<typename HighType > static stxxl::uint_pair<HighType> std::numeric_limits< stxxl::uint_pair< HighType > >::lowest () inline static
return an uint_pair instance containing the smallest value possible
Definition at line 279 of file uint_types.h.
References min().
template<typename HighType > static stxxl::uint_pair<HighType> std::numeric_limits< stxxl::uint_pair< HighType > >::max () inline static
return an uint_pair instance containing the largest value possible
Definition at line 275 of file uint_types.h.
References stxxl::uint_pair< HighType >::max().
template<typename HighType > static stxxl::uint_pair<HighType> std::numeric_limits< stxxl::uint_pair< HighType > >::min () inline static
return an uint_pair instance containing the smallest value possible
Definition at line 271 of file uint_types.h.
References stxxl::uint_pair< HighType >::min().
template<typename HighType > static const stxxl::uint_pair<HighType> std::numeric_limits< stxxl::uint_pair< HighType > >::round_error () inline static
rounding error is zero
Definition at line 302 of file uint_types.h.
Member Data Documentation
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::digits = stxxl::uint_pair<HighType>::digits static
number of binary digits (bits) in uint_pair
Definition at line 295 of file uint_types.h.
template<typename HighType > const bool std::numeric_limits< stxxl::uint_pair< HighType > >::has_infinity = false static
no infinity
Definition at line 318 of file uint_types.h.
template<typename HighType > const bool std::numeric_limits< stxxl::uint_pair< HighType > >::is_exact = true static
unit_pair types contain exact integers
Definition at line 289 of file uint_types.h.
template<typename HighType > const bool std::numeric_limits< stxxl::uint_pair< HighType > >::is_integer = true static
uint_pair types are integers
Definition at line 286 of file uint_types.h.
template<typename HighType > const bool std::numeric_limits< stxxl::uint_pair< HighType > >::is_signed = false static
unit_pair types are unsigned
Definition at line 283 of file uint_types.h.
template<typename HighType > const bool std::numeric_limits< stxxl::uint_pair< HighType > >::is_specialized = true static
yes we have information about uint_pair
Definition at line 268 of file uint_types.h.
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::max_exponent = 0 static
no exponent
Definition at line 312 of file uint_types.h.
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::max_exponent10 = 0 static
no exponent
Definition at line 315 of file uint_types.h.
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::min_exponent = 0 static
no exponent
Definition at line 306 of file uint_types.h.
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::min_exponent10 = 0 static
no exponent
Definition at line 309 of file uint_types.h.
template<typename HighType > const int std::numeric_limits< stxxl::uint_pair< HighType > >::radix = 2 static
unit_pair radix is binary
Definition at line 292 of file uint_types.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/common/uint_types.h