STXXL: stxxl::btree::btree_const_iterator< BTreeType > Class Template Reference
stxxl::btree::btree_const_iterator< BTreeType > Class Template Reference
Detailed Description
template<class BTreeType>
class stxxl::btree::btree_const_iterator< BTreeType >
Definition at line 30 of file iterator.h.
Public Types
typedef btree_iterator_base
< btree_type > base_type
typedef btree_type::leaf_bid_type bid_type
typedef BTreeType btree_type
typedef btree_iterator< BTreeType > iterator
typedef btree_type::const_pointer pointer
typedef btree_type::const_reference reference
typedef btree_type::value_type value_type
Public Types inherited from stxxl::btree::btree_iterator_base< BTreeType >
typedef btree_type::leaf_bid_type bid_type
typedef BTreeType btree_type
typedef btree_type::const_reference const_reference
typedef btree_type::difference_type difference_type
typedef
std::bidirectional_iterator_tag iterator_category
typedef btree_type::leaf_type leaf_type
typedef btree_type::reference reference
typedef btree_type::value_type value_type
Public Member Functions
btree_const_iterator ()
btree_const_iterator (const btree_const_iterator &obj)
btree_const_iterator (const iterator &obj)
bool operator!= (const iterator &obj) const
bool operator!= (const btree_const_iterator &obj) const
reference operator* ()
btree_const_iterator & operator++ ()
btree_const_iterator operator++ (int)
btree_const_iterator & operator-- ()
btree_const_iterator operator-- (int)
pointer operator-> ()
btree_const_iterator & operator= (const btree_const_iterator &obj)
bool operator== (const iterator &obj) const
bool operator== (const btree_const_iterator &obj) const
Public Member Functions inherited from stxxl::btree::btree_iterator_base< BTreeType >
virtual ~btree_iterator_base ()
Private Member Functions
btree_const_iterator (btree_type *_btree, const bid_type &_bid, unsigned_type _pos)
Additional Inherited Members
Protected Member Functions inherited from stxxl::btree::btree_iterator_base< BTreeType >
btree_iterator_base ()
btree_iterator_base (btree_type *_btree, const bid_type &_bid, unsigned_type _pos)
btree_iterator_base (const btree_iterator_base &obj)
const_reference const_access () const
btree_iterator_base & decrement ()
btree_iterator_base & increment ()
void make_invalid ()
reference non_const_access ()
bool operator!= (const btree_iterator_base &obj) const
btree_iterator_base & operator= (const btree_iterator_base &obj)
bool operator== (const btree_iterator_base &obj) const
Protected Attributes inherited from stxxl::btree::btree_iterator_base< BTreeType >
bid_type bid
btree_type * btree
unsigned_type pos
Member Typedef Documentation
template<class BTreeType> typedef btree_iterator_base<btree_type> stxxl::btree::btree_const_iterator< BTreeType >::base_type
Definition at line 272 of file iterator.h.
template<class BTreeType> typedef btree_type::leaf_bid_type stxxl::btree::btree_const_iterator< BTreeType >::bid_type
Definition at line 267 of file iterator.h.
template<class BTreeType> typedef BTreeType stxxl::btree::btree_const_iterator< BTreeType >::btree_type
Definition at line 266 of file iterator.h.
template<class BTreeType> typedef btree_iterator<BTreeType> stxxl::btree::btree_const_iterator< BTreeType >::iterator
Definition at line 264 of file iterator.h.
template<class BTreeType> typedef btree_type::const_pointer stxxl::btree::btree_const_iterator< BTreeType >::pointer
Definition at line 270 of file iterator.h.
template<class BTreeType> typedef btree_type::const_reference stxxl::btree::btree_const_iterator< BTreeType >::reference
Definition at line 269 of file iterator.h.
template<class BTreeType> typedef btree_type::value_type stxxl::btree::btree_const_iterator< BTreeType >::value_type
Definition at line 268 of file iterator.h.
Constructor & Destructor Documentation
template<class BTreeType> stxxl::btree::btree_const_iterator< BTreeType >::btree_const_iterator () inline
Definition at line 280 of file iterator.h.
template<class BTreeType> stxxl::btree::btree_const_iterator< BTreeType >::btree_const_iterator (const btree_const_iterator< BTreeType > & obj) inline
Definition at line 284 of file iterator.h.
template<class BTreeType> stxxl::btree::btree_const_iterator< BTreeType >::btree_const_iterator (const iterator & obj) inline
Definition at line 288 of file iterator.h.
template<class BTreeType> stxxl::btree::btree_const_iterator< BTreeType >::btree_const_iterator (btree_type * _btree, const bid_type & _bid, unsigned_type _pos) inline private
Definition at line 357 of file iterator.h.
Member Function Documentation
template<class BTreeType> bool stxxl::btree::btree_const_iterator< BTreeType >::operator!= (const iterator & obj) const inline
Definition at line 313 of file iterator.h.
References operator!=().
template<class BTreeType> bool stxxl::btree::btree_const_iterator< BTreeType >::operator!= (const btree_const_iterator< BTreeType > & obj) const inline
Definition at line 323 of file iterator.h.
References operator!=().
template<class BTreeType> reference stxxl::btree::btree_const_iterator< BTreeType >::operator* () inline
Definition at line 298 of file iterator.h.
template<class BTreeType> btree_const_iterator& stxxl::btree::btree_const_iterator< BTreeType >::operator++ () inline
Definition at line 328 of file iterator.h.
template<class BTreeType> btree_const_iterator stxxl::btree::btree_const_iterator< BTreeType >::operator++ (int) inline
Definition at line 341 of file iterator.h.
template<class BTreeType> btree_const_iterator& stxxl::btree::btree_const_iterator< BTreeType >::operator-- () inline
Definition at line 335 of file iterator.h.
template<class BTreeType> btree_const_iterator stxxl::btree::btree_const_iterator< BTreeType >::operator-- (int) inline
Definition at line 349 of file iterator.h.
template<class BTreeType> pointer stxxl::btree::btree_const_iterator< BTreeType >::operator-> () inline
Definition at line 303 of file iterator.h.
template<class BTreeType> btree_const_iterator& stxxl::btree::btree_const_iterator< BTreeType >::operator= (const btree_const_iterator< BTreeType > & obj) inline
Definition at line 292 of file iterator.h.
template<class BTreeType> bool stxxl::btree::btree_const_iterator< BTreeType >::operator== (const iterator & obj) const inline
Definition at line 308 of file iterator.h.
References operator==().
template<class BTreeType> bool stxxl::btree::btree_const_iterator< BTreeType >::operator== (const btree_const_iterator< BTreeType > & obj) const inline
Definition at line 318 of file iterator.h.
References operator==().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/btree/iterator.h