STXXL: stxxl::mng_local::element_block< Type, Size > Class Template Reference
stxxl::mng_local::element_block< Type, Size > Class Template Reference
Internals
Detailed Description
template<typename Type, unsigned Size>
class stxxl::mng_local::element_block< Type, Size >
Contains data elements for stxxl::typed_block , not intended for direct use.
Definition at line 64 of file typed_block.h.
Public Types
enum { size = Size }
typedef const type * const_iterator
typedef const Type & const_reference
typedef pointer iterator
typedef type * pointer
typedef Type & reference
typedef Type type
typedef Type value_type
Public Member Functions
element_block ()
iterator begin ()
Returns iterator pointing to the first element.
const_iterator begin () const
Returns const_iterator pointing to the first element.
const_iterator cbegin () const
Returns const_iterator pointing to the first element.
const_iterator cend () const
Returns const_iterator pointing to the end element.
iterator end ()
Returns iterator pointing to the end element.
const_iterator end () const
Returns const_iterator pointing to the end element.
reference operator[] (size_t i)
An operator to access elements in the block.
Public Attributes
value_type elem [size]
Array of elements of type Type.
Member Typedef Documentation
template<typename Type , unsigned Size> typedef const type* stxxl::mng_local::element_block< Type, Size >::const_iterator
Definition at line 73 of file typed_block.h.
template<typename Type , unsigned Size> typedef const Type& stxxl::mng_local::element_block< Type, Size >::const_reference
Definition at line 70 of file typed_block.h.
template<typename Type , unsigned Size> typedef pointer stxxl::mng_local::element_block< Type, Size >::iterator
Definition at line 72 of file typed_block.h.
template<typename Type , unsigned Size> typedef type* stxxl::mng_local::element_block< Type, Size >::pointer
Definition at line 71 of file typed_block.h.
template<typename Type , unsigned Size> typedef Type& stxxl::mng_local::element_block< Type, Size >::reference
Definition at line 69 of file typed_block.h.
template<typename Type , unsigned Size> typedef Type stxxl::mng_local::element_block< Type, Size >::type
Definition at line 67 of file typed_block.h.
template<typename Type , unsigned Size> typedef Type stxxl::mng_local::element_block< Type, Size >::value_type
Definition at line 68 of file typed_block.h.
Member Enumeration Documentation
template<typename Type , unsigned Size> anonymous enum
Enumerator
size
number of elements in the block
Definition at line 75 of file typed_block.h.
Constructor & Destructor Documentation
template<typename Type , unsigned Size> stxxl::mng_local::element_block< Type, Size >::element_block () inline
Definition at line 83 of file typed_block.h.
References STXXL_VERBOSE_TYPED_BLOCK.
Member Function Documentation
template<typename Type , unsigned Size> iterator stxxl::mng_local::element_block< Type, Size >::begin () inline
Returns iterator pointing to the first element.
Definition at line 92 of file typed_block.h.
Referenced by stxxl::btree::normal_leaf< KeyType, DataType, KeyCmp, LogNElem, BTreeType >::balance(), stxxl::btree::normal_node< KeyType, KeyCmp, RawSize, BTreeType >::balance(), stxxl::stream::basic_runs_creator< Input, CompareType, BlockSize, AllocStr >::compute_result(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::erase(), stxxl::btree::normal_leaf< KeyType, DataType, KeyCmp, LogNElem, BTreeType >::fuse(), stxxl::btree::normal_node< KeyType, KeyCmp, RawSize, BTreeType >::fuse(), stxxl::btree::normal_node< KeyType, KeyCmp, RawSize, BTreeType >::insert(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::insert_into_root(), and stxxl::btree::normal_leaf< KeyType, DataType, KeyCmp, LogNElem, BTreeType >::split().
template<typename Type , unsigned Size> const_iterator stxxl::mng_local::element_block< Type, Size >::begin () const inline
Returns const_iterator pointing to the first element.
Definition at line 98 of file typed_block.h.
template<typename Type , unsigned Size> const_iterator stxxl::mng_local::element_block< Type, Size >::cbegin () const inline
Returns const_iterator pointing to the first element.
Definition at line 104 of file typed_block.h.
template<typename Type , unsigned Size> const_iterator stxxl::mng_local::element_block< Type, Size >::cend () const inline
Returns const_iterator pointing to the end element.
Definition at line 122 of file typed_block.h.
template<typename Type , unsigned Size> iterator stxxl::mng_local::element_block< Type, Size >::end () inline
Returns iterator pointing to the end element.
Definition at line 110 of file typed_block.h.
template<typename Type , unsigned Size> const_iterator stxxl::mng_local::element_block< Type, Size >::end () const inline
Returns const_iterator pointing to the end element.
Definition at line 116 of file typed_block.h.
template<typename Type , unsigned Size> reference stxxl::mng_local::element_block< Type, Size >::operator[] (size_t i) inline
An operator to access elements in the block.
Definition at line 86 of file typed_block.h.
Member Data Documentation
template<typename Type , unsigned Size> value_type stxxl::mng_local::element_block< Type, Size >::elem[size]
Array of elements of type Type.
Definition at line 81 of file typed_block.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/mng/typed_block.h