STXXL: stxxl::btree::iterator_map< BTreeType > Class Template Reference
stxxl::btree::iterator_map< BTreeType > Class Template Reference
Detailed Description
template<class BTreeType>
class stxxl::btree::iterator_map< BTreeType >
Definition at line 26 of file iterator.h.
Classes
struct bid_comp
struct Key
struct KeyCmp
Public Types
typedef btree_type::leaf_bid_type bid_type
typedef BTreeType btree_type
typedef btree_iterator_base
< btree_type > iterator_base
Public Member Functions
iterator_map (btree_type *b)
virtual ~iterator_map ()
template<class OutputContainer >
void find (const bid_type &bid, unsigned_type first_pos, unsigned_type last_pos, OutputContainer &out)
void register_iterator (iterator_base &it)
void swap (iterator_map &obj)
void unregister_iterator (iterator_base &it)
Private Types
typedef
multimap_type::const_iterator mmconst_iterator_type
typedef multimap_type::iterator mmiterator_type
typedef std::multimap< Key,
iterator_base *, KeyCmp > multimap_type
typedef multimap_type::value_type pair_type
Private Member Functions
void change_btree_pointers (btree_type *b)
changes btree pointer in all contained iterators
Private Member Functions inherited from stxxl::noncopyable
noncopyable ()
Private Attributes
btree_type * m_btree
multimap_type m_it2addr
Member Typedef Documentation
template<class BTreeType> typedef btree_type::leaf_bid_type stxxl::btree::iterator_map< BTreeType >::bid_type
Definition at line 31 of file iterator_map.h.
template<class BTreeType> typedef BTreeType stxxl::btree::iterator_map< BTreeType >::btree_type
Definition at line 30 of file iterator_map.h.
template<class BTreeType> typedef btree_iterator_base<btree_type> stxxl::btree::iterator_map< BTreeType >::iterator_base
Definition at line 32 of file iterator_map.h.
template<class BTreeType> typedef multimap_type::const_iterator stxxl::btree::iterator_map< BTreeType >::mmconst_iterator_type private
Definition at line 67 of file iterator_map.h.
template<class BTreeType> typedef multimap_type::iterator stxxl::btree::iterator_map< BTreeType >::mmiterator_type private
Definition at line 66 of file iterator_map.h.
template<class BTreeType> typedef std::multimap<Key, iterator_base*, KeyCmp> stxxl::btree::iterator_map< BTreeType >::multimap_type private
Definition at line 60 of file iterator_map.h.
template<class BTreeType> typedef multimap_type::value_type stxxl::btree::iterator_map< BTreeType >::pair_type private
Definition at line 65 of file iterator_map.h.
Constructor & Destructor Documentation
template<class BTreeType> stxxl::btree::iterator_map< BTreeType >::iterator_map (btree_type * b) inline
Definition at line 80 of file iterator_map.h.
template<class BTreeType> virtual stxxl::btree::iterator_map< BTreeType >::~iterator_map () inline virtual
Definition at line 136 of file iterator_map.h.
Member Function Documentation
template<class BTreeType> void stxxl::btree::iterator_map< BTreeType >::change_btree_pointers (btree_type * b) inline private
changes btree pointer in all contained iterators
Definition at line 70 of file iterator_map.h.
template<class BTreeType> template<class OutputContainer > void stxxl::btree::iterator_map< BTreeType >::find (const bid_type & bid, unsigned_type first_pos, unsigned_type last_pos, OutputContainer & out) inline
Definition at line 118 of file iterator_map.h.
template<class BTreeType> void stxxl::btree::iterator_map< BTreeType >::register_iterator (iterator_base & it) inline
Definition at line 84 of file iterator_map.h.
Referenced by stxxl::btree::btree_iterator_base< self_type >::btree_iterator_base(), and stxxl::btree::btree_iterator_base< self_type >::operator=().
template<class BTreeType> void stxxl::btree::iterator_map< BTreeType >::swap (iterator_map< BTreeType > & obj) inline
Definition at line 145 of file iterator_map.h.
template<class BTreeType> void stxxl::btree::iterator_map< BTreeType >::unregister_iterator (iterator_base & it) inline
Definition at line 90 of file iterator_map.h.
Referenced by stxxl::btree::btree_iterator_base< self_type >::operator=(), and stxxl::btree::btree_iterator_base< self_type >::~btree_iterator_base().
Member Data Documentation
template<class BTreeType> btree_type* stxxl::btree::iterator_map< BTreeType >::m_btree private
Definition at line 63 of file iterator_map.h.
template<class BTreeType> multimap_type stxxl::btree::iterator_map< BTreeType >::m_it2addr private
Definition at line 62 of file iterator_map.h.
The documentation for this class was generated from the following files:
include/stxxl/bits/containers/btree/iterator.h
include/stxxl/bits/containers/btree/iterator_map.h