STXXL: stxxl::row_vector< ValueType > Class Template Reference
stxxl::row_vector< ValueType > Class Template Reference
matrix
Detailed Description
template<typename ValueType>
class stxxl::row_vector< ValueType >
external row-vector container for matrix multiplication
Template Parameters
ValueType type of contained objects (POD with no references to internal memory)
Definition at line 120 of file matrix.h.
Public Types
typedef vector_type::size_type size_type
typedef vector< ValueType > vector_type
Public Types inherited from stxxl::vector< ValueType >
enum constants
typedef ValueType value_type
The type of elements stored in the vector.
typedef value_type & reference
reference to value_type
typedef const value_type & const_reference
constant reference to value_type
typedef value_type * pointer
pointer to value_type
typedef const value_type * const_pointer
constant pointer to value_type
typedef SizeType size_type
an unsigned 64-bit integral type
typedef stxxl::int64 difference_type
typedef PagerType pager_type
typedef AllocStr alloc_strategy_type
typedef vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > iterator
iterator used to iterate through a vector, see More Notes.
typedef const_vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > const_iterator
constant iterator used to iterate through a vector, see More Notes.
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef vector_bufwriter
< iterator > bufwriter_type
vector_bufwriter compatible with this vector
typedef vector_bufreader
< const_iterator > bufreader_type
vector_bufreader compatible with this vector
typedef
vector_bufreader_reverse
< const_iterator > bufreader_reverse_type
vector_bufreader compatible with this vector
typedef bid_vector bids_container_type
typedef
bids_container_type::iterator bids_container_iterator
typedef
bids_container_type::const_iterator const_bids_container_iterator
typedef typed_block< BlockSize,
ValueType > block_type
type of the block used in disk-memory transfers
typedef double_blocked_index
< SizeType, PageSize,
block_type::size > blocked_index_type
double-index type to reference individual elements in a block
Public Member Functions
row_vector (size_type n=0)
row_vector operator* (const ValueType scalar) const
template<unsigned BlockSideLength>
row_vector operator* (const matrix< ValueType, BlockSideLength > &right) const
ValueType operator* (const column_vector< ValueType > &right) const
row_vector & operator*= (const ValueType scalar)
row_vector operator+ (const row_vector &right) const
row_vector & operator+= (const row_vector &right)
row_vector operator- (const row_vector &right) const
row_vector & operator-= (const row_vector &right)
void set_zero ()
Public Member Functions inherited from stxxl::vector< ValueType >
vector (size_type n=0, unsigned_type npages=pager_type().size())
Constructs external vector with n elements.
vector (file *from, size_type size=size_type(-1), unsigned_type npages=pager_type().size())
Construct vector from a file.
vector (const vector &obj)
copy-constructor
~vector ()
void swap (vector &obj)
swap content
void allocate_page_cache () const
Allocate page cache, must be called to allow access to elements.
void deallocate_page_cache () const
allows to free the cache, but you may not access any element until call allocate_page_cache() again
void export_files (std::string filename_prefix)
Export data such that it is persistent on the file system. Resulting files will be numbered ascending.
file * get_file () const
Get the file associated with this vector, or NULL.
size_type size () const
return the size of the vector.
bool empty () const
true if the vector's size is zero.
size_type capacity () const
Return the number of elelemtsn for which external memory has been allocated. capacity() is always greator than or equal to size().
size_type raw_capacity () const
Returns the number of bytes that the vector has allocated on disks.
void reserve (size_type n)
Reserves at least n elements in external memory.
void resize (size_type n)
Resize vector contents to n items.
void resize (size_type n, bool shrink_capacity)
Resize vector contents to n items, and allow the allocated external memory to shrink. Internal memory allocation remains unchanged.
void clear ()
Erases all of the elements and deallocates all external memory that is occupied.
void flush () const
Flushes the cache pages to the external memory.
void push_back (const_reference obj)
Append a new element at the end.
void pop_back ()
Removes the last element (without returning it, see back()).
reference back ()
Returns a reference to the last element, see More Notes.
const_reference back () const
Returns a constant reference to the last element, see More Notes.
reference front ()
Returns a reference to the first element, see More Notes.
const_reference front () const
Returns a constant reference to the first element, see More Notes.
vector & operator= (const vector &obj)
assignment operator
iterator begin ()
returns an iterator pointing to the beginning of the vector, see More Notes.
const_iterator begin () const
returns a const_iterator pointing to the beginning of the vector, see More Notes.
const_iterator cbegin () const
returns a const_iterator pointing to the beginning of the vector, see More Notes.
iterator end ()
returns an iterator pointing beyond the end of the vector, see More Notes.
const_iterator end () const
returns a const_iterator pointing beyond the end of the vector, see More Notes.
const_iterator cend () const
returns a const_iterator pointing beyond the end of the vector, see More Notes.
reverse_iterator rbegin ()
returns a reverse_iterator pointing to the end of the vector.
const_reverse_iterator rbegin () const
returns a reverse_iterator pointing to the end of the vector.
const_reverse_iterator crbegin () const
returns a reverse_iterator pointing to the end of the vector.
reverse_iterator rend ()
returns a reverse_iterator pointing beyond the beginning of the vector.
const_reverse_iterator rend () const
returns a reverse_iterator pointing beyond the beginning of the vector.
const_reverse_iterator crend () const
returns a reverse_iterator pointing beyond the beginning of the vector.
reference operator[] (size_type offset)
access the element at the given vector's offset
const_reference operator[] (size_type offset) const
access the element at the given vector's offset
reference at (size_type offset)
access the element at the given vector's offset
const_reference at (size_type offset) const
access the element at the given vector's offset
bool is_element_cached (size_type offset) const
return true if the given vector offset is in cache
void set_content (const ForwardIterator &bid_begin, const ForwardIterator &bid_end, size_type n)
Set the blocks and the size of this container explicitly. The vector must be completely empty before.
unsigned_type numpages () const
Number of pages used by the pager.
Member Typedef Documentation
template<typename ValueType > typedef vector_type::size_type stxxl::row_vector< ValueType >::size_type
Definition at line 124 of file matrix.h.
template<typename ValueType > typedef vector<ValueType> stxxl::row_vector< ValueType >::vector_type
Definition at line 123 of file matrix.h.
Constructor & Destructor Documentation
template<typename ValueType > stxxl::row_vector< ValueType >::row_vector (size_type n = 0) inline
Parameters
n number of elements
Definition at line 129 of file matrix.h.
Member Function Documentation
template<typename ValueType > row_vector stxxl::row_vector< ValueType >::operator* (const ValueType scalar) const inline
Definition at line 150 of file matrix.h.
template<typename ValueType > template<unsigned BlockSideLength> row_vector stxxl::row_vector< ValueType >::operator* (const matrix< ValueType, BlockSideLength > & right) const inline
Definition at line 159 of file matrix.h.
References stxxl::matrix< ValueType, BlockSideLength >::multiply_from_left().
template<typename ValueType > ValueType stxxl::row_vector< ValueType >::operator* (const column_vector< ValueType > & right) const inline
Definition at line 162 of file matrix.h.
template<typename ValueType > row_vector& stxxl::row_vector< ValueType >::operator*= (const ValueType scalar) inline
Definition at line 186 of file matrix.h.
template<typename ValueType > row_vector stxxl::row_vector< ValueType >::operator+ (const row_vector< ValueType > & right) const inline
Definition at line 132 of file matrix.h.
References stxxl::vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType > row_vector& stxxl::row_vector< ValueType >::operator+= (const row_vector< ValueType > & right) inline
Definition at line 170 of file matrix.h.
References stxxl::vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType > row_vector stxxl::row_vector< ValueType >::operator- (const row_vector< ValueType > & right) const inline
Definition at line 141 of file matrix.h.
References stxxl::vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType > row_vector& stxxl::row_vector< ValueType >::operator-= (const row_vector< ValueType > & right) inline
Definition at line 178 of file matrix.h.
References stxxl::vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType > void stxxl::row_vector< ValueType >::set_zero () inline
Definition at line 193 of file matrix.h.
Referenced by stxxl::matrix< ValueType, BlockSideLength >::multiply_from_left().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/matrix.h