STXXL: stxxl::stats_data Class Reference
stxxl::stats_data Class Reference
I/O Primitives Layer
Detailed Description
Examples:
examples/applications/skew3.cpp.
Definition at line 428 of file iostats.h.
Public Member Functions
stats_data ()
stats_data (const stats &s)
int64 get_cached_read_volume () const
unsigned get_cached_reads () const
unsigned get_cached_writes () const
int64 get_cached_written_volume () const
double get_elapsed_time () const
double get_io_wait_time () const
double get_pio_time () const
double get_pread_time () const
double get_pwrite_time () const
double get_read_time () const
int64 get_read_volume () const
unsigned get_reads () const
double get_wait_read_time () const
double get_wait_write_time () const
double get_write_time () const
unsigned get_writes () const
int64 get_written_volume () const
stats_data operator+ (const stats_data &a) const
stats_data operator- (const stats_data &a) const
Private Attributes
unsigned c_reads
number of cached operations
int64 c_volume_read
number of bytes read/written from/to cache
int64 c_volume_written
unsigned c_writes
double elapsed
double p_ios
seconds spent in all parallel I/O operations (read and write)
double p_reads
seconds spent in parallel operations
double p_writes
unsigned reads
number of operations
double t_reads
seconds spent in operations
double t_wait
seconds spent waiting for completion of I/O operations
double t_wait_read
double t_wait_write
double t_writes
int64 volume_read
number of bytes read/written
int64 volume_written
unsigned writes
Constructor & Destructor Documentation
stxxl::stats_data::stats_data () inline
Definition at line 450 of file iostats.h.
stxxl::stats_data::stats_data (const stats & s) inline
Definition at line 470 of file iostats.h.
Member Function Documentation
int64 stxxl::stats_data::get_cached_read_volume () const inline
Definition at line 566 of file iostats.h.
Referenced by stxxl::operator<<().
unsigned stxxl::stats_data::get_cached_reads () const inline
Definition at line 556 of file iostats.h.
Referenced by stxxl::operator<<().
unsigned stxxl::stats_data::get_cached_writes () const inline
Definition at line 561 of file iostats.h.
Referenced by stxxl::operator<<().
int64 stxxl::stats_data::get_cached_written_volume () const inline
Definition at line 571 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_elapsed_time () const inline
Definition at line 601 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_io_wait_time () const inline
Definition at line 606 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_pio_time () const inline
Definition at line 596 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_pread_time () const inline
Definition at line 586 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_pwrite_time () const inline
Definition at line 591 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_read_time () const inline
Definition at line 576 of file iostats.h.
Referenced by stxxl::operator<<().
int64 stxxl::stats_data::get_read_volume () const inline
Definition at line 546 of file iostats.h.
Referenced by stxxl::operator<<().
unsigned stxxl::stats_data::get_reads () const inline
Definition at line 536 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_wait_read_time () const inline
Definition at line 611 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_wait_write_time () const inline
Definition at line 616 of file iostats.h.
Referenced by stxxl::operator<<().
double stxxl::stats_data::get_write_time () const inline
Definition at line 581 of file iostats.h.
Referenced by stxxl::operator<<().
unsigned stxxl::stats_data::get_writes () const inline
Definition at line 541 of file iostats.h.
Referenced by stxxl::operator<<().
int64 stxxl::stats_data::get_written_volume () const inline
Definition at line 551 of file iostats.h.
Referenced by stxxl::operator<<().
stats_data stxxl::stats_data::operator+ (const stats_data & a) const inline
Definition at line 490 of file iostats.h.
References c_reads, c_volume_read, c_volume_written, c_writes, elapsed, p_ios, p_reads, p_writes, reads, t_reads, t_wait, t_wait_read, t_wait_write, t_writes, volume_read, volume_written, and writes.
stats_data stxxl::stats_data::operator- (const stats_data & a) const inline
Definition at line 513 of file iostats.h.
References c_reads, c_volume_read, c_volume_written, c_writes, elapsed, p_ios, p_reads, p_writes, reads, t_reads, t_wait, t_wait_read, t_wait_write, t_writes, volume_read, volume_written, and writes.
Member Data Documentation
unsigned stxxl::stats_data::c_reads private
number of cached operations
Definition at line 435 of file iostats.h.
Referenced by operator+(), and operator-().
int64 stxxl::stats_data::c_volume_read private
number of bytes read/written from/to cache
Definition at line 437 of file iostats.h.
Referenced by operator+(), and operator-().
int64 stxxl::stats_data::c_volume_written private
Definition at line 437 of file iostats.h.
Referenced by operator+(), and operator-().
unsigned stxxl::stats_data::c_writes private
Definition at line 435 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::elapsed private
Definition at line 447 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::p_ios private
seconds spent in all parallel I/O operations (read and write)
Definition at line 443 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::p_reads private
seconds spent in parallel operations
Definition at line 441 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::p_writes private
Definition at line 441 of file iostats.h.
Referenced by operator+(), and operator-().
unsigned stxxl::stats_data::reads private
number of operations
Definition at line 431 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::t_reads private
seconds spent in operations
Definition at line 439 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::t_wait private
seconds spent waiting for completion of I/O operations
Definition at line 445 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::t_wait_read private
Definition at line 446 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::t_wait_write private
Definition at line 446 of file iostats.h.
Referenced by operator+(), and operator-().
double stxxl::stats_data::t_writes private
Definition at line 439 of file iostats.h.
Referenced by operator+(), and operator-().
int64 stxxl::stats_data::volume_read private
number of bytes read/written
Definition at line 433 of file iostats.h.
Referenced by operator+(), and operator-().
int64 stxxl::stats_data::volume_written private
Definition at line 433 of file iostats.h.
Referenced by operator+(), and operator-().
unsigned stxxl::stats_data::writes private
Definition at line 431 of file iostats.h.
Referenced by operator+(), and operator-().
The documentation for this class was generated from the following file:
include/stxxl/bits/io/iostats.h