STXXL: stxxl::state< ValueType > Class Template Reference
stxxl::state< ValueType > Class Template Reference
Detailed Description
template<typename ValueType = int>
class stxxl::state< ValueType >
Definition at line 25 of file state.h.
Public Member Functions
state (const value_type &s)
value_type operator() ()
void set_to (const value_type &new_state)
void wait_for (const value_type &needed_state)
Private Types
typedef ValueType value_type
Private Attributes
condition_variable m_cond
condition variable
mutex m_mutex
mutex for condition variable
value_type m_state
current state
Additional Inherited Members
Private Member Functions inherited from stxxl::noncopyable
noncopyable ()
Member Typedef Documentation
template<typename ValueType = int> typedef ValueType stxxl::state< ValueType >::value_type private
Definition at line 27 of file state.h.
Constructor & Destructor Documentation
template<typename ValueType = int> stxxl::state< ValueType >::state (const value_type & s) inline
Definition at line 39 of file state.h.
Member Function Documentation
template<typename ValueType = int> value_type stxxl::state< ValueType >::operator() () inline
Definition at line 58 of file state.h.
template<typename ValueType = int> void stxxl::state< ValueType >::set_to (const value_type & new_state) inline
Definition at line 43 of file state.h.
Referenced by stxxl::linuxaio_queue::post_async(), stxxl::request_queue_impl_worker::start_thread(), stxxl::request_queue_impl_worker::stop_thread(), and stxxl::linuxaio_queue::wait_async().
template<typename ValueType = int> void stxxl::state< ValueType >::wait_for (const value_type & needed_state) inline
Definition at line 51 of file state.h.
Member Data Documentation
template<typename ValueType = int> condition_variable stxxl::state< ValueType >::m_cond private
condition variable
Definition at line 33 of file state.h.
template<typename ValueType = int> mutex stxxl::state< ValueType >::m_mutex private
mutex for condition variable
Definition at line 30 of file state.h.
template<typename ValueType = int> value_type stxxl::state< ValueType >::m_state private
current state
Definition at line 36 of file state.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/common/state.h