STXXL: stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize > Class Template Reference
stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize > Class Template Reference
Detailed Description
template<typename ValueType, unsigned_type MaxSize>
class stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >
Similar to std::stack, with the following differences:
Maximum size is fixed at compilation time, so an array can be used.
Can be cleared "at once", without reallocation.
Definition at line 208 of file pq_helpers.h.
Public Member Functions
internal_bounded_stack ()
void clear ()
bool empty () const
void pop ()
void push (const value_type &x)
size_type size () const
const value_type & top () const
Private Types
enum { max_size = MaxSize }
typedef unsigned_type size_type
typedef ValueType value_type
Private Attributes
value_type m_array [max_size]
size_type m_size
Member Typedef Documentation
template<typename ValueType, unsigned_type MaxSize> typedef unsigned_type stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::size_type private
Definition at line 211 of file pq_helpers.h.
template<typename ValueType, unsigned_type MaxSize> typedef ValueType stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::value_type private
Definition at line 210 of file pq_helpers.h.
Member Enumeration Documentation
template<typename ValueType, unsigned_type MaxSize> anonymous enum private
Enumerator
max_size
Definition at line 212 of file pq_helpers.h.
Constructor & Destructor Documentation
template<typename ValueType, unsigned_type MaxSize> stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::internal_bounded_stack () inline
Definition at line 218 of file pq_helpers.h.
Member Function Documentation
template<typename ValueType, unsigned_type MaxSize> void stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::clear () inline
Definition at line 238 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::compact_tree().
template<typename ValueType, unsigned_type MaxSize> bool stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::empty () const inline
Definition at line 248 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::double_k(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::insert_segment(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::is_space_available(), and stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::multi_merge().
template<typename ValueType, unsigned_type MaxSize> void stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::pop () inline
Definition at line 232 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::insert_segment().
template<typename ValueType, unsigned_type MaxSize> void stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::push (const value_type & x) inline
Definition at line 220 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::compact_tree(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::deallocate_segment(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::double_k(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::init(), and stxxl::priority_queue_local::loser_tree< ValueType, CompareType, MaxArity >::loser_tree().
template<typename ValueType, unsigned_type MaxSize> size_type stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::size () const inline
Definition at line 243 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::compact_tree(), stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::double_k(), and stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::multi_merge().
template<typename ValueType, unsigned_type MaxSize> const value_type& stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::top () const inline
Definition at line 226 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType, Cmp, Arity, AllocStr >::insert_segment().
Member Data Documentation
template<typename ValueType, unsigned_type MaxSize> value_type stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::m_array[max_size] private
Definition at line 215 of file pq_helpers.h.
template<typename ValueType, unsigned_type MaxSize> size_type stxxl::priority_queue_local::internal_bounded_stack< ValueType, MaxSize >::m_size private
Definition at line 214 of file pq_helpers.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/pq_helpers.h