STXXL: stxxl::hash_map::hash_map_const_iterator< HashMap > Class Template Reference
stxxl::hash_map::hash_map_const_iterator< HashMap > Class Template Reference
Detailed Description
template<class HashMap>
class stxxl::hash_map::hash_map_const_iterator< HashMap >
Definition at line 31 of file iterator.h.
Public Types
typedef
stxxl::hash_map::hash_map_iterator_base
< hash_map_type > base_type
typedef
hash_map_type::bid_iterator_type bid_iterator_type
typedef hash_map_type::bucket_type bucket_type
typedef
hash_map_type::const_pointer const_pointer
typedef
hash_map_type::const_reference const_reference
typedef
hash_map_type::external_size_type external_size_type
typedef
stxxl::hash_map::hash_map_iterator
< hash_map_type > hash_map_iterator
typedef HashMap hash_map_type
typedef
hash_map_type::internal_size_type internal_size_type
typedef std::forward_iterator_tag iterator_category
typedef hash_map_type::key_type key_type
typedef hash_map_type::node_type node_type
typedef hash_map_type::pointer pointer
typedef buffered_reader
< typename
hash_map_type::block_cache_type,
bid_iterator_type > reader_type
typedef hash_map_type::reference reference
typedef hash_map_type::source_type source_type
typedef hash_map_type::value_type value_type
Public Types inherited from stxxl::hash_map::hash_map_iterator_base< HashMap >
typedef
hash_map_type::bid_iterator_type bid_iterator_type
typedef hash_map_type::bucket_type bucket_type
typedef
hash_map_type::const_reference const_reference
typedef
hash_map_type::external_size_type external_size_type
typedef HashMap hash_map_type
typedef
hash_map_type::internal_size_type internal_size_type
typedef std::forward_iterator_tag iterator_category
typedef hash_map_type::key_type key_type
typedef hash_map_type::node_type node_type
typedef buffered_reader
< typename
hash_map_type::block_cache_type,
bid_iterator_type > reader_type
typedef hash_map_type::reference reference
typedef hash_map_type::source_type source_type
typedef hash_map_type::value_type value_type
Public Member Functions
hash_map_const_iterator (hash_map_type *map, internal_size_type i_bucket, node_type *node, external_size_type i_external, source_type source, bool ext_valid, key_type key)
hash_map_const_iterator ()
hash_map_const_iterator (hash_map_type *map)
hash_map_const_iterator (const hash_map_iterator &obj)
hash_map_const_iterator (const hash_map_const_iterator &obj)
bool operator!= (const hash_map_const_iterator &obj) const
bool operator!= (const hash_map_iterator &obj) const
const_reference operator* ()
Return const-reference to current value.
hash_map_const_iterator
< hash_map_type > & operator++ ()
Increment iterator.
hash_map_const_iterator & operator= (const hash_map_const_iterator &obj)
bool operator== (const hash_map_const_iterator &obj) const
bool operator== (const hash_map_iterator &obj) const
Public Member Functions inherited from stxxl::hash_map::hash_map_iterator_base< HashMap >
hash_map_iterator_base (HashMap *map, internal_size_type i_bucket, node_type *node, external_size_type i_external, source_type source, bool ext_valid, key_type key)
Construct a new iterator.
hash_map_iterator_base (hash_map_type *map)
Construct a new iterator pointing to the end of the given hash-map.
hash_map_iterator_base (const hash_map_iterator_base &obj)
Construct a new iterator from an existing one.
virtual ~hash_map_iterator_base ()
void find_next (bool start_prefetching=false)
Advance iterator to the next value The next value is determined in the following way.
bool operator!= (const hash_map_iterator_base &obj) const
hash_map_iterator_base & operator= (const hash_map_iterator_base &obj)
Assignment operator.
bool operator== (const hash_map_iterator_base &obj) const
Two iterators are equal if the point to the same value in the same map.
Additional Inherited Members
Protected Member Functions inherited from stxxl::hash_map::hash_map_iterator_base< HashMap >
void init_reader ()
Initialize reader object to scan external values.
void reset_reader ()
Reset reader-object.
Protected Attributes inherited from stxxl::hash_map::hash_map_iterator_base< HashMap >
bool end_
true if iterator equals end()
bool ext_valid_
true if i_external points to the current or next external value
internal_size_type i_bucket_
index of current bucket
external_size_type i_external_
position of current (source=external) or next (source=internal) external value (see _ext_valid)
key_type key_
key of current value
HashMap * map_
node_type * node_
current (source=internal) or old (src=external) internal node
bool prefetch_
true if prefetching enabled; false by default, will be set to true when incrementing (see find_next())
reader_type * reader_
source_type source_
source of current value: external or internal
Member Typedef Documentation
template<class HashMap> typedef stxxl::hash_map::hash_map_iterator_base<hash_map_type> stxxl::hash_map::hash_map_const_iterator< HashMap >::base_type
Definition at line 507 of file iterator.h.
template<class HashMap> typedef hash_map_type::bid_iterator_type stxxl::hash_map::hash_map_const_iterator< HashMap >::bid_iterator_type
Definition at line 499 of file iterator.h.
template<class HashMap> typedef hash_map_type::bucket_type stxxl::hash_map::hash_map_const_iterator< HashMap >::bucket_type
Definition at line 498 of file iterator.h.
template<class HashMap> typedef hash_map_type::const_pointer stxxl::hash_map::hash_map_const_iterator< HashMap >::const_pointer
Definition at line 496 of file iterator.h.
template<class HashMap> typedef hash_map_type::const_reference stxxl::hash_map::hash_map_const_iterator< HashMap >::const_reference
Definition at line 494 of file iterator.h.
template<class HashMap> typedef hash_map_type::external_size_type stxxl::hash_map::hash_map_const_iterator< HashMap >::external_size_type
Definition at line 490 of file iterator.h.
template<class HashMap> typedef stxxl::hash_map::hash_map_iterator<hash_map_type> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_iterator
Definition at line 508 of file iterator.h.
template<class HashMap> typedef HashMap stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_type
Definition at line 488 of file iterator.h.
template<class HashMap> typedef hash_map_type::internal_size_type stxxl::hash_map::hash_map_const_iterator< HashMap >::internal_size_type
Definition at line 489 of file iterator.h.
template<class HashMap> typedef std::forward_iterator_tag stxxl::hash_map::hash_map_const_iterator< HashMap >::iterator_category
Definition at line 505 of file iterator.h.
template<class HashMap> typedef hash_map_type::key_type stxxl::hash_map::hash_map_const_iterator< HashMap >::key_type
Definition at line 492 of file iterator.h.
template<class HashMap> typedef hash_map_type::node_type stxxl::hash_map::hash_map_const_iterator< HashMap >::node_type
Definition at line 497 of file iterator.h.
template<class HashMap> typedef hash_map_type::pointer stxxl::hash_map::hash_map_const_iterator< HashMap >::pointer
Definition at line 495 of file iterator.h.
template<class HashMap> typedef buffered_reader<typename hash_map_type::block_cache_type, bid_iterator_type> stxxl::hash_map::hash_map_const_iterator< HashMap >::reader_type
Definition at line 503 of file iterator.h.
template<class HashMap> typedef hash_map_type::reference stxxl::hash_map::hash_map_const_iterator< HashMap >::reference
Definition at line 493 of file iterator.h.
template<class HashMap> typedef hash_map_type::source_type stxxl::hash_map::hash_map_const_iterator< HashMap >::source_type
Definition at line 500 of file iterator.h.
template<class HashMap> typedef hash_map_type::value_type stxxl::hash_map::hash_map_const_iterator< HashMap >::value_type
Definition at line 491 of file iterator.h.
Constructor & Destructor Documentation
template<class HashMap> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_const_iterator (hash_map_type * map, internal_size_type i_bucket, node_type * node, external_size_type i_external, source_type source, bool ext_valid, key_type key) inline
Definition at line 511 of file iterator.h.
template<class HashMap> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_const_iterator () inline
Definition at line 517 of file iterator.h.
template<class HashMap> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_const_iterator (hash_map_type * map) inline
Definition at line 521 of file iterator.h.
template<class HashMap> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_const_iterator (const hash_map_iterator & obj) inline
Definition at line 525 of file iterator.h.
template<class HashMap> stxxl::hash_map::hash_map_const_iterator< HashMap >::hash_map_const_iterator (const hash_map_const_iterator< HashMap > & obj) inline
Definition at line 529 of file iterator.h.
Member Function Documentation
template<class HashMap> bool stxxl::hash_map::hash_map_const_iterator< HashMap >::operator!= (const hash_map_const_iterator< HashMap > & obj) const inline
Definition at line 549 of file iterator.h.
References operator!=().
template<class HashMap> bool stxxl::hash_map::hash_map_const_iterator< HashMap >::operator!= (const hash_map_iterator & obj) const inline
Definition at line 554 of file iterator.h.
References operator!=().
template<class HashMap> const_reference stxxl::hash_map::hash_map_const_iterator< HashMap >::operator* () inline
Return const-reference to current value.
Definition at line 560 of file iterator.h.
template<class HashMap> hash_map_const_iterator<hash_map_type>& stxxl::hash_map::hash_map_const_iterator< HashMap >::operator++ () inline
Increment iterator.
Definition at line 576 of file iterator.h.
template<class HashMap> hash_map_const_iterator& stxxl::hash_map::hash_map_const_iterator< HashMap >::operator= (const hash_map_const_iterator< HashMap > & obj) inline
Definition at line 533 of file iterator.h.
template<class HashMap> bool stxxl::hash_map::hash_map_const_iterator< HashMap >::operator== (const hash_map_const_iterator< HashMap > & obj) const inline
Definition at line 539 of file iterator.h.
References operator==().
template<class HashMap> bool stxxl::hash_map::hash_map_const_iterator< HashMap >::operator== (const hash_map_iterator & obj) const inline
Definition at line 544 of file iterator.h.
References operator==().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/hash_map/iterator.h