STXXL: Common Utilities and Support Classes
Common Utilities and Support Classes
Supporting classes also useful for applications, see also Common Utilities and Helpers .
Classes
class stxxl::atomic_counted_object
Provides reference counting abilities for use with counting_ptr with mutex locking.
class stxxl::binary_buffer
binary_buffer represents a dynamically growable area of memory, which can be modified by appending integral data types via put() and other basic operations.
class stxxl::binary_buffer_ref
binary_buffer_ref represents a memory area as pointer and valid length.
class stxxl::binary_reader
binary_reader represents a binary_buffer_ref with an additional cursor with which the memory can be read incrementally.
class stxxl::cmdline_parser
class stxxl::const_counting_ptr< Type >
High-performance smart pointer used as a wrapping reference counting pointer.
class stxxl::counted_object
Provides reference counting abilities for use with counting_ptr.
class stxxl::counting_ptr< Type >
High-performance smart pointer used as a wrapping reference counting pointer.
class stxxl::external_shared_ptr< P >
This class takes a shared pointer, increments its reference count and wraps it in a way that the resulting object can be copied, dumped to disk, and destroyed without affecting the refcount.
struct stxxl::random_number< UniformRGen >
Uniform [0, N) pseudo-random generator.
struct stxxl::random_number32
Fast uniform [0, 2^32) pseudo-random generator with period 2^32, random bits: 32.
struct stxxl::random_number32_r
Fast uniform [0, 2^32) pseudo-random generator with period 2^32, random bits: 32. Reentrant variant of random_number32 that keeps it's private state.
struct stxxl::random_number64
Slow and precise uniform [0, 2^64) pseudo-random generator.
class stxxl::random_number8_r
Fast uniform [0, 255] pseudo-random generator with period 2^8, random bits: 8 (one byte).
struct stxxl::random_uniform_fast
Fast uniform [0.0, 1.0) pseudo-random generator.
struct stxxl::random_uniform_slow
Slow and precise uniform [0.0, 1.0) pseudo-random generator period: at least 2^48, random bits: at least 31.
class stxxl::scoped_print_timer
Simple scoped timer, which takes a text message and prints the duration until the scope is destroyed.
class stxxl::simple_vector< ValueType >
Simpler non-growing vector without initialization.
class stxxl::timer
Typedefs
typedef uint_pair< uint8 > stxxl::uint40
Construct a 40-bit unsigned integer stored in five bytes.
typedef uint_pair< uint16 > stxxl::uint48
Construct a 48-bit unsigned integer stored in six bytes.
Functions
void stxxl::srandom_number32 (unsigned seed=0)
Set a seed value for random_number32.
template<class A >
void stxxl::swap (counting_ptr< A > &a1, counting_ptr< A > &a2)
swap enclosed object with another counting pointer (no reference counts need change)
template<class A >
void stxxl::swap (const_counting_ptr< A > &a1, const_counting_ptr< A > &a2)
swap enclosed object with another const_counting pointer (no reference counts need change)
double stxxl::timestamp ()
Returns number of seconds since the epoch, high resolution.
Detailed Description
Supporting classes also useful for applications, see also Common Utilities and Helpers .
Typedef Documentation
typedef uint_pair<uint8> stxxl::uint40
Construct a 40-bit unsigned integer stored in five bytes.
Definition at line 251 of file uint_types.h.
typedef uint_pair<uint16> stxxl::uint48
Construct a 48-bit unsigned integer stored in six bytes.
Definition at line 254 of file uint_types.h.
Function Documentation
void stxxl::srandom_number32 (unsigned seed = 0) inline
Set a seed value for random_number32.
Definition at line 66 of file rand.h.
References stxxl::get_next_seed(), and stxxl::ran32State.
template<class A > void stxxl::swap (counting_ptr< A > & a1, counting_ptr< A > & a2)
swap enclosed object with another counting pointer (no reference counts need change)
Definition at line 165 of file counting_ptr.h.
References stxxl::counting_ptr< Type >::swap().
template<class A > void stxxl::swap (const_counting_ptr< A > & a1, const_counting_ptr< A > & a2)
swap enclosed object with another const_counting pointer (no reference counts need change)
Definition at line 315 of file counting_ptr.h.
References stxxl::const_counting_ptr< Type >::swap().
double stxxl::timestamp () inline
Returns number of seconds since the epoch, high resolution.
Examples:
examples/algo/phonebills.cpp, and examples/algo/phonebills_genlog.cpp.
Definition at line 44 of file timer.h.
Referenced by stxxl::ksort_local::ksort_blocks(), stxxl::timer::mseconds(), stxxl::linuxaio_request::post(), stxxl::print_msg(), stxxl::timer::reset(), stxxl::stats::reset(), stxxl::timer::seconds(), stxxl::sort_local::sort_blocks(), stxxl::stable_ksort(), stxxl::timer::start(), stxxl::timer::stop(), stxxl::timer::timestamp(), stxxl::timer::useconds(), stxxl::stats::wait_finished(), and stxxl::stats::wait_started().