STXXL: I/O Requests and Queues
I/O Requests and Queues
I/O Primitives Layer
Encapsulation of an I/O request, queues for requests and threads to process them.
Classes
class stxxl::disk_queues
Encapsulates disk queues.
class stxxl::linuxaio_queue
Queue for linuxaio_file(s)
class stxxl::linuxaio_request
Request for an linuxaio_file.
class stxxl::request
Request object encapsulating basic properties like file and offset.
class stxxl::request_interface
Functional interface of a request.
class stxxl::request_queue
Interface of a request_queue to which requests can be added and canceled.
class stxxl::request_queue_impl_1q
Implementation of a local request queue having only one queue for both read and write requests, thus having only one thread.
class stxxl::request_queue_impl_qwqr
Implementation of a local request queue having two queues, one for read and one for write requests, thus having two threads. This is the default implementation.
class stxxl::request_queue_impl_worker
Implementation of request queue worker threads. Worker threads can be started by start_thread and stopped with stop_thread. The queue state is checked before termination and updated afterwards.
class stxxl::request_with_state
Request with completion state.
class stxxl::request_with_waiters
Request that is aware of threads waiting for it to complete.
class stxxl::serving_request
Request which serves an I/O by calling the synchronous routine of the file.
Macros
#define STXXL_BLOCK_ALIGN 4096
Typedefs
typedef counting_ptr< request > stxxl::request_ptr
A reference counting pointer for request.
Functions
template<class RequestIterator >
std::iterator_traits
< RequestIterator >
::difference_type stxxl::cancel_all (RequestIterator reqs_begin, RequestIterator reqs_end)
Cancel requests. The specified requests are canceled unless already being processed. However, cancelation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
std::ostream & stxxl::operator<< (std::ostream &out, const request &req)
template<class RequestIterator >
RequestIterator stxxl::poll_any (RequestIterator reqs_begin, RequestIterator reqs_end)
Polls requests.
bool stxxl::poll_any (request_ptr req_array[], size_t count, size_t &index)
Polls requests.
template<class RequestIterator >
void stxxl::wait_all (RequestIterator reqs_begin, RequestIterator reqs_end)
Collection of functions to track statuses of a number of requests.
void stxxl::wait_all (request_ptr req_array[], size_t count)
Suspends calling thread until all given requests are completed.
template<class RequestIterator >
RequestIterator stxxl::wait_any (RequestIterator reqs_begin, RequestIterator reqs_end)
Suspends calling thread until any of requests is completed.
size_t stxxl::wait_any (request_ptr req_array[], size_t count)
Suspends calling thread until any of requests is completed.
Detailed Description
Encapsulation of an I/O request, queues for requests and threads to process them.
Macro Definition Documentation
#define STXXL_BLOCK_ALIGN 4096
Definition at line 33 of file request.h.
Referenced by stxxl::request::check_alignment(), stxxl::mem_file::discard(), stxxl::fileperblock_file< base_file_type >::lock(), and stxxl::typed_block< RawSize, Type, NRef, MetaInfoType >::typed_block().
Typedef Documentation
typedef counting_ptr<request> stxxl::request_ptr
A reference counting pointer for request.
Definition at line 113 of file request.h.
Function Documentation
template<class RequestIterator > std::iterator_traits<RequestIterator>::difference_type stxxl::cancel_all (RequestIterator reqs_begin, RequestIterator reqs_end)
Cancel requests. The specified requests are canceled unless already being processed. However, cancelation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
Parameters
reqs_begin begin of request sequence
reqs_end end of request sequence
Returns
number of request canceled
Definition at line 58 of file request_operations.h.
std::ostream& stxxl::operator<< (std::ostream & out, const request & req) inline
Definition at line 107 of file request.h.
References stxxl::request::print().
template<class RequestIterator > RequestIterator stxxl::poll_any (RequestIterator reqs_begin, RequestIterator reqs_end)
Polls requests.
Parameters
reqs_begin begin of request sequence to poll
reqs_end end of request sequence to poll
Returns
true if any of requests is completed, then index contains valid value, otherwise false
Definition at line 75 of file request_operations.h.
Referenced by stxxl::poll_any().
bool stxxl::poll_any (request_ptr req_array[], size_t count, size_t & index) inline
Polls requests.
Parameters
req_array array of request_ptr objects
count size of req_array
index contains index of the first completed request if any
Returns
true if any of requests is completed, then index contains valid value, otherwise false
Definition at line 92 of file request_operations.h.
References stxxl::count(), and stxxl::poll_any().
template<class RequestIterator > void stxxl::wait_all (RequestIterator reqs_begin, RequestIterator reqs_end)
Collection of functions to track statuses of a number of requests.
Suspends calling thread until all given requests are completed.
Parameters
reqs_begin begin of request sequence to wait for
reqs_end end of request sequence to wait for
Definition at line 34 of file request_operations.h.
Referenced by stxxl::ksort_local::check_ksorted_runs(), stxxl::sort_local::check_sorted_runs(), stxxl::stream::check_sorted_runs(), stxxl::stream::basic_runs_creator< Input, CompareType, BlockSize, AllocStr >::compute_result(), stxxl::sort_local::create_runs(), stxxl::ksort_local::create_runs(), stxxl::ksort(), stxxl::normal_stack< StackConfig >::pop(), stxxl::grow_shrink_stack< StackConfig >::pop(), stxxl::normal_stack< StackConfig >::push(), stxxl::vector< ValueType >::read_page(), stxxl::stl_in_memory_sort(), stxxl::wait_all(), stxxl::vector< ValueType >::write_page(), and stxxl::grow_shrink_stack< StackConfig >::~grow_shrink_stack().
void stxxl::wait_all (request_ptr req_array[], size_t count) inline
Suspends calling thread until all given requests are completed.
Parameters
req_array array of request_ptr objects
count size of req_array
Definition at line 43 of file request_operations.h.
References stxxl::wait_all().
template<class RequestIterator > RequestIterator stxxl::wait_any (RequestIterator reqs_begin, RequestIterator reqs_end)
Suspends calling thread until any of requests is completed.
Parameters
reqs_begin begin of request sequence to wait for
reqs_end end of request sequence to wait for
Returns
index in req_array pointing to the first completed request
Definition at line 104 of file request_operations.h.
References stxxl::onoff_switch::wait_for_on().
Referenced by stxxl::buffered_writer< block_type >::get_free_block(), stxxl::write_pool< BlockType >::steal(), and stxxl::wait_any().
size_t stxxl::wait_any (request_ptr req_array[], size_t count) inline
Suspends calling thread until any of requests is completed.
Parameters
req_array array of request_ptr objects
count size of req_array
Returns
index in req_array pointing to the first completed request
Definition at line 149 of file request_operations.h.
References stxxl::wait_any().