STXXL: stxxl::sort_local Namespace Reference
stxxl::sort_local Namespace Reference
Algorithms
Classes
struct read_next_after_write_completed
Functions
template<typename BlockType , typename RunType , typename ValueCmp >
bool check_sorted_runs (RunType **runs, unsigned_type nruns, unsigned_type m, ValueCmp cmp)
template<typename BlockType , typename RunType , typename InputBidIterator , typename ValueCmp >
void create_runs (InputBidIterator it, RunType **runs, int_type nruns, int_type _m, ValueCmp cmp)
template<typename BlockType , typename RunType , typename ValueCmp >
void merge_runs (RunType **in_runs, int_type nruns, RunType *out_run, unsigned_type _m, ValueCmp cmp)
template<typename BlockType , typename AllocStrategy , typename InputBidIterator , typename ValueCmp >
simple_vector
< sort_helper::trigger_entry
< BlockType > > * sort_blocks (InputBidIterator input_bids, unsigned_type _n, unsigned_type _m, ValueCmp cmp)
Detailed Description
Function Documentation
template<typename BlockType , typename RunType , typename ValueCmp > bool stxxl::sort_local::check_sorted_runs (RunType ** runs, unsigned_type nruns, unsigned_type m, ValueCmp cmp)
Definition at line 207 of file sort.h.
References stxxl::is_sorted(), stxxl::make_element_iterator(), stxxl::STXXL_MIN(), STXXL_MSG, and stxxl::wait_all().
Referenced by stxxl::stream::basic_runs_merger< typename runs_creator_type::sorted_runs_type, cmp_type, alloc_strategy_type >::initialize().
template<typename BlockType , typename RunType , typename InputBidIterator , typename ValueCmp > void stxxl::sort_local::create_runs (InputBidIterator it, RunType ** runs, int_type nruns, int_type _m, ValueCmp cmp)
Definition at line 70 of file sort.h.
References stxxl::sort_local::read_next_after_write_completed< BlockType, BidType >::bid, stxxl::sort_local::read_next_after_write_completed< BlockType, BidType >::block, stxxl::check_sort_settings(), stxxl::block_manager::delete_block(), stxxl::make_element_iterator(), stxxl::sort_local::read_next_after_write_completed< BlockType, BidType >::req, stxxl::sort(), STXXL_ASSERT, STXXL_VERBOSE1, and stxxl::wait_all().
template<typename BlockType , typename RunType , typename ValueCmp > void stxxl::sort_local::merge_runs (RunType ** in_runs, int_type nruns, RunType * out_run, unsigned_type _m, ValueCmp cmp)
Definition at line 307 of file sort.h.
References _STXXL_SORT_TRIGGER_FORCE_SEQUENTIAL, stxxl::compute_prefetch_schedule(), stxxl::sort_helper::count_elements_less_equal(), stxxl::block_manager::delete_block(), stxxl::do_parallel_merge(), stxxl::is_sorted(), stxxl::loser_tree< RunCursorType, RunCursorCmpType >::multi_merge(), stxxl::sort_helper::refill_or_remove_empty_sequences(), stxxl::STXXL_MAX(), stxxl::STXXL_MIN(), STXXL_THROW_UNREACHABLE, and STXXL_VERBOSE1.
template<typename BlockType , typename AllocStrategy , typename InputBidIterator , typename ValueCmp > simple_vector<sort_helper::trigger_entry<BlockType> >* stxxl::sort_local::sort_blocks (InputBidIterator input_bids, unsigned_type _n, unsigned_type _m, ValueCmp cmp)
Definition at line 513 of file sort.h.
References stxxl::ksort_local::create_runs(), stxxl::div_ceil(), stxxl::make_bid_iterator(), stxxl::block_manager::new_block(), stxxl::block_manager::new_blocks(), stxxl::optimal_merge_factor(), stxxl::STXXL_MIN(), STXXL_VERBOSE, and stxxl::timestamp().
Referenced by stxxl::sort().