var namespacestxxl =
[
    [ "async_schedule_local", "namespacestxxl_1_1async__schedule__local.html", null ],
    [ "btree", "namespacestxxl_1_1btree.html", "namespacestxxl_1_1btree" ],
    [ "compat", "namespacestxxl_1_1compat.html", "namespacestxxl_1_1compat" ],
    [ "hash_map", "namespacestxxl_1_1hash__map.html", "namespacestxxl_1_1hash__map" ],
    [ "helper", "namespacestxxl_1_1helper.html", "namespacestxxl_1_1helper" ],
    [ "ksort_local", "namespacestxxl_1_1ksort__local.html", "namespacestxxl_1_1ksort__local" ],
    [ "matrix_local", "namespacestxxl_1_1matrix__local.html", "namespacestxxl_1_1matrix__local" ],
    [ "mng_local", "namespacestxxl_1_1mng__local.html", "namespacestxxl_1_1mng__local" ],
    [ "parallel", "namespacestxxl_1_1parallel.html", null ],
    [ "potentially_parallel", "namespacestxxl_1_1potentially__parallel.html", null ],
    [ "priority_queue_local", "namespacestxxl_1_1priority__queue__local.html", "namespacestxxl_1_1priority__queue__local" ],
    [ "sort_helper", "namespacestxxl_1_1sort__helper.html", "namespacestxxl_1_1sort__helper" ],
    [ "sort_local", "namespacestxxl_1_1sort__local.html", "namespacestxxl_1_1sort__local" ],
    [ "stable_ksort_local", "namespacestxxl_1_1stable__ksort__local.html", "namespacestxxl_1_1stable__ksort__local" ],
    [ "stream", "namespacestxxl_1_1stream.html", "namespacestxxl_1_1stream" ],
    [ "addressable_fifo_queue", "classstxxl_1_1addressable__fifo__queue.html", "classstxxl_1_1addressable__fifo__queue" ],
    [ "addressable_priority_queue", "classstxxl_1_1addressable__priority__queue.html", "classstxxl_1_1addressable__priority__queue" ],
    [ "aligned_alloc_settings", "structstxxl_1_1aligned__alloc__settings.html", "structstxxl_1_1aligned__alloc__settings" ],
    [ "array_of_sequences_iterator", "classstxxl_1_1array__of__sequences__iterator.html", "classstxxl_1_1array__of__sequences__iterator" ],
    [ "atomic_counted_object", "classstxxl_1_1atomic__counted__object.html", "classstxxl_1_1atomic__counted__object" ],
    [ "bad_ext_alloc", "classstxxl_1_1bad__ext__alloc.html", "classstxxl_1_1bad__ext__alloc" ],
    [ "bad_parameter", "classstxxl_1_1bad__parameter.html", "classstxxl_1_1bad__parameter" ],
    [ "basic_allocation_strategy", "structstxxl_1_1basic__allocation__strategy.html", "structstxxl_1_1basic__allocation__strategy" ],
    [ "BID", "structstxxl_1_1BID.html", "structstxxl_1_1BID" ],
    [ "BID< 0 >", "structstxxl_1_1BID_3_010_01_4.html", "structstxxl_1_1BID_3_010_01_4" ],
    [ "BIDArray", "classstxxl_1_1BIDArray.html", "classstxxl_1_1BIDArray" ],
    [ "binary_buffer", "classstxxl_1_1binary__buffer.html", "classstxxl_1_1binary__buffer" ],
    [ "binary_buffer_ref", "classstxxl_1_1binary__buffer__ref.html", "classstxxl_1_1binary__buffer__ref" ],
    [ "binary_reader", "classstxxl_1_1binary__reader.html", "classstxxl_1_1binary__reader" ],
    [ "block_manager", "classstxxl_1_1block__manager.html", "classstxxl_1_1block__manager" ],
    [ "block_prefetcher", "classstxxl_1_1block__prefetcher.html", "classstxxl_1_1block__prefetcher" ],
    [ "block_scheduler", "classstxxl_1_1block__scheduler.html", "classstxxl_1_1block__scheduler" ],
    [ "block_scheduler_algorithm", "classstxxl_1_1block__scheduler__algorithm.html", "classstxxl_1_1block__scheduler__algorithm" ],
    [ "block_scheduler_algorithm_offline_lfd", "classstxxl_1_1block__scheduler__algorithm__offline__lfd.html", "classstxxl_1_1block__scheduler__algorithm__offline__lfd" ],
    [ "block_scheduler_algorithm_offline_lru_prefetching", "classstxxl_1_1block__scheduler__algorithm__offline__lru__prefetching.html", "classstxxl_1_1block__scheduler__algorithm__offline__lru__prefetching" ],
    [ "block_scheduler_algorithm_online_lru", "classstxxl_1_1block__scheduler__algorithm__online__lru.html", "classstxxl_1_1block__scheduler__algorithm__online__lru" ],
    [ "block_scheduler_algorithm_simulation", "classstxxl_1_1block__scheduler__algorithm__simulation.html", "classstxxl_1_1block__scheduler__algorithm__simulation" ],
    [ "blocked_index", "classstxxl_1_1blocked__index.html", "classstxxl_1_1blocked__index" ],
    [ "buf_istream", "classstxxl_1_1buf__istream.html", "classstxxl_1_1buf__istream" ],
    [ "buf_istream_reverse", "classstxxl_1_1buf__istream__reverse.html", "classstxxl_1_1buf__istream__reverse" ],
    [ "buf_ostream", "classstxxl_1_1buf__ostream.html", "classstxxl_1_1buf__ostream" ],
    [ "buffered_writer", "classstxxl_1_1buffered__writer.html", "classstxxl_1_1buffered__writer" ],
    [ "CASE", "structstxxl_1_1CASE.html", "structstxxl_1_1CASE" ],
    [ "choose_int_types", "structstxxl_1_1choose__int__types.html", null ],
    [ "choose_int_types< 4 >", "structstxxl_1_1choose__int__types_3_014_01_4.html", "structstxxl_1_1choose__int__types_3_014_01_4" ],
    [ "choose_int_types< 8 >", "structstxxl_1_1choose__int__types_3_018_01_4.html", "structstxxl_1_1choose__int__types_3_018_01_4" ],
    [ "cmdline_parser", "classstxxl_1_1cmdline__parser.html", "classstxxl_1_1cmdline__parser" ],
    [ "column_vector", "classstxxl_1_1column__vector.html", "classstxxl_1_1column__vector" ],
    [ "compat_hash", "structstxxl_1_1compat__hash.html", "structstxxl_1_1compat__hash" ],
    [ "compat_hash_map", "structstxxl_1_1compat__hash__map.html", "structstxxl_1_1compat__hash__map" ],
    [ "compat_hash_multimap", "structstxxl_1_1compat__hash__multimap.html", "structstxxl_1_1compat__hash__multimap" ],
    [ "compat_unique_ptr", "structstxxl_1_1compat__unique__ptr.html", "structstxxl_1_1compat__unique__ptr" ],
    [ "completion_handler", "classstxxl_1_1completion__handler.html", "classstxxl_1_1completion__handler" ],
    [ "completion_handler1", "classstxxl_1_1completion__handler1.html", "classstxxl_1_1completion__handler1" ],
    [ "completion_handler_impl", "classstxxl_1_1completion__handler__impl.html", "classstxxl_1_1completion__handler__impl" ],
    [ "condition_variable", "classstxxl_1_1condition__variable.html", "classstxxl_1_1condition__variable" ],
    [ "config", "classstxxl_1_1config.html", "classstxxl_1_1config" ],
    [ "const_counting_ptr", "classstxxl_1_1const__counting__ptr.html", "classstxxl_1_1const__counting__ptr" ],
    [ "const_deque_iterator", "classstxxl_1_1const__deque__iterator.html", "classstxxl_1_1const__deque__iterator" ],
    [ "const_matrix_col_major_iterator", "classstxxl_1_1const__matrix__col__major__iterator.html", "classstxxl_1_1const__matrix__col__major__iterator" ],
    [ "const_matrix_iterator", "classstxxl_1_1const__matrix__iterator.html", "classstxxl_1_1const__matrix__iterator" ],
    [ "const_matrix_row_major_iterator", "classstxxl_1_1const__matrix__row__major__iterator.html", "classstxxl_1_1const__matrix__row__major__iterator" ],
    [ "const_vector_iterator", "classstxxl_1_1const__vector__iterator.html", "classstxxl_1_1const__vector__iterator" ],
    [ "counted_object", "classstxxl_1_1counted__object.html", "classstxxl_1_1counted__object" ],
    [ "counting_ptr", "classstxxl_1_1counting__ptr.html", "classstxxl_1_1counting__ptr" ],
    [ "deque", "classstxxl_1_1deque.html", "classstxxl_1_1deque" ],
    [ "deque_iterator", "classstxxl_1_1deque__iterator.html", "classstxxl_1_1deque__iterator" ],
    [ "disk_allocator", "classstxxl_1_1disk__allocator.html", "classstxxl_1_1disk__allocator" ],
    [ "disk_config", "classstxxl_1_1disk__config.html", "classstxxl_1_1disk__config" ],
    [ "disk_queued_file", "classstxxl_1_1disk__queued__file.html", "classstxxl_1_1disk__queued__file" ],
    [ "disk_queues", "classstxxl_1_1disk__queues.html", "classstxxl_1_1disk__queues" ],
    [ "double_blocked_index", "classstxxl_1_1double__blocked__index.html", "classstxxl_1_1double__blocked__index" ],
    [ "element_iterator_traits", "structstxxl_1_1element__iterator__traits.html", "structstxxl_1_1element__iterator__traits" ],
    [ "external_shared_ptr", "classstxxl_1_1external__shared__ptr.html", "classstxxl_1_1external__shared__ptr" ],
    [ "file", "classstxxl_1_1file.html", "classstxxl_1_1file" ],
    [ "fileperblock_file", "classstxxl_1_1fileperblock__file.html", "classstxxl_1_1fileperblock__file" ],
    [ "first_disk_only", "structstxxl_1_1first__disk__only.html", "structstxxl_1_1first__disk__only" ],
    [ "FR", "structstxxl_1_1FR.html", "structstxxl_1_1FR" ],
    [ "grow_shrink_stack", "classstxxl_1_1grow__shrink__stack.html", "classstxxl_1_1grow__shrink__stack" ],
    [ "grow_shrink_stack2", "classstxxl_1_1grow__shrink__stack2.html", "classstxxl_1_1grow__shrink__stack2" ],
    [ "IC35L080AVVA07", "classstxxl_1_1IC35L080AVVA07.html", "classstxxl_1_1IC35L080AVVA07" ],
    [ "IF", "structstxxl_1_1IF.html", "structstxxl_1_1IF" ],
    [ "IF< false, Type1, Type2 >", "structstxxl_1_1IF_3_01false_00_01Type1_00_01Type2_01_4.html", "structstxxl_1_1IF_3_01false_00_01Type1_00_01Type2_01_4" ],
    [ "IF_N", "structstxxl_1_1IF__N.html", "structstxxl_1_1IF__N" ],
    [ "IF_N< false, Num1, Num2 >", "structstxxl_1_1IF__N_3_01false_00_01Num1_00_01Num2_01_4.html", "structstxxl_1_1IF__N_3_01false_00_01Num1_00_01Num2_01_4" ],
    [ "interleaved_alloc_traits", "structstxxl_1_1interleaved__alloc__traits.html", null ],
    [ "interleaved_alloc_traits< FR >", "structstxxl_1_1interleaved__alloc__traits_3_01FR_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01FR_01_4" ],
    [ "interleaved_alloc_traits< RC >", "structstxxl_1_1interleaved__alloc__traits_3_01RC_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01RC_01_4" ],
    [ "interleaved_alloc_traits< RC_disk >", "structstxxl_1_1interleaved__alloc__traits_3_01RC__disk_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01RC__disk_01_4" ],
    [ "interleaved_alloc_traits< RC_flash >", "structstxxl_1_1interleaved__alloc__traits_3_01RC__flash_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01RC__flash_01_4" ],
    [ "interleaved_alloc_traits< single_disk >", "structstxxl_1_1interleaved__alloc__traits_3_01single__disk_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01single__disk_01_4" ],
    [ "interleaved_alloc_traits< SR >", "structstxxl_1_1interleaved__alloc__traits_3_01SR_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01SR_01_4" ],
    [ "interleaved_alloc_traits< striping >", "structstxxl_1_1interleaved__alloc__traits_3_01striping_01_4.html", "structstxxl_1_1interleaved__alloc__traits_3_01striping_01_4" ],
    [ "interleaved_FR", "structstxxl_1_1interleaved__FR.html", "structstxxl_1_1interleaved__FR" ],
    [ "interleaved_RC", "structstxxl_1_1interleaved__RC.html", "structstxxl_1_1interleaved__RC" ],
    [ "interleaved_SR", "structstxxl_1_1interleaved__SR.html", "structstxxl_1_1interleaved__SR" ],
    [ "interleaved_striping", "structstxxl_1_1interleaved__striping.html", "structstxxl_1_1interleaved__striping" ],
    [ "io_error", "classstxxl_1_1io__error.html", "classstxxl_1_1io__error" ],
    [ "ksort_defaultkey", "structstxxl_1_1ksort__defaultkey.html", "structstxxl_1_1ksort__defaultkey" ],
    [ "linuxaio_file", "classstxxl_1_1linuxaio__file.html", "classstxxl_1_1linuxaio__file" ],
    [ "linuxaio_queue", "classstxxl_1_1linuxaio__queue.html", "classstxxl_1_1linuxaio__queue" ],
    [ "linuxaio_request", "classstxxl_1_1linuxaio__request.html", "classstxxl_1_1linuxaio__request" ],
    [ "LOG2", "classstxxl_1_1LOG2.html", "classstxxl_1_1LOG2" ],
    [ "LOG2< 0 >", "classstxxl_1_1LOG2_3_010_01_4.html", "classstxxl_1_1LOG2_3_010_01_4" ],
    [ "LOG2< 1 >", "classstxxl_1_1LOG2_3_011_01_4.html", "classstxxl_1_1LOG2_3_011_01_4" ],
    [ "LOG2_floor", "classstxxl_1_1LOG2__floor.html", "classstxxl_1_1LOG2__floor" ],
    [ "LOG2_floor< 0 >", "classstxxl_1_1LOG2__floor_3_010_01_4.html", "classstxxl_1_1LOG2__floor_3_010_01_4" ],
    [ "LOG2_floor< 1 >", "classstxxl_1_1LOG2__floor_3_011_01_4.html", "classstxxl_1_1LOG2__floor_3_011_01_4" ],
    [ "logger", "classstxxl_1_1logger.html", "classstxxl_1_1logger" ],
    [ "loser_tree", "classstxxl_1_1loser__tree.html", "classstxxl_1_1loser__tree" ],
    [ "lru_pager", "classstxxl_1_1lru__pager.html", "classstxxl_1_1lru__pager" ],
    [ "malloc_setup", "classstxxl_1_1malloc__setup.html", null ],
    [ "malloc_stats", "classstxxl_1_1malloc__stats.html", null ],
    [ "map", "classstxxl_1_1map.html", "classstxxl_1_1map" ],
    [ "matrix", "classstxxl_1_1matrix.html", "classstxxl_1_1matrix" ],
    [ "matrix_col_major_iterator", "classstxxl_1_1matrix__col__major__iterator.html", "classstxxl_1_1matrix__col__major__iterator" ],
    [ "matrix_iterator", "classstxxl_1_1matrix__iterator.html", "classstxxl_1_1matrix__iterator" ],
    [ "matrix_operation_statistic", "structstxxl_1_1matrix__operation__statistic.html", null ],
    [ "matrix_operation_statistic_data", "structstxxl_1_1matrix__operation__statistic__data.html", "structstxxl_1_1matrix__operation__statistic__data" ],
    [ "matrix_operation_statistic_dataset", "structstxxl_1_1matrix__operation__statistic__dataset.html", "structstxxl_1_1matrix__operation__statistic__dataset" ],
    [ "matrix_row_major_iterator", "classstxxl_1_1matrix__row__major__iterator.html", "classstxxl_1_1matrix__row__major__iterator" ],
    [ "matrix_swappable_block", "classstxxl_1_1matrix__swappable__block.html", "classstxxl_1_1matrix__swappable__block" ],
    [ "mem_file", "classstxxl_1_1mem__file.html", "classstxxl_1_1mem__file" ],
    [ "migrating_stack", "classstxxl_1_1migrating__stack.html", "classstxxl_1_1migrating__stack" ],
    [ "mmap_file", "classstxxl_1_1mmap__file.html", "classstxxl_1_1mmap__file" ],
    [ "mutex", "classstxxl_1_1mutex.html", "classstxxl_1_1mutex" ],
    [ "new_alloc", "classstxxl_1_1new__alloc.html", "classstxxl_1_1new__alloc" ],
    [ "new_alloc_rebind", "structstxxl_1_1new__alloc__rebind.html", "structstxxl_1_1new__alloc__rebind" ],
    [ "new_alloc_rebind< Type, Type >", "structstxxl_1_1new__alloc__rebind_3_01Type_00_01Type_01_4.html", "structstxxl_1_1new__alloc__rebind_3_01Type_00_01Type_01_4" ],
    [ "NilCase", "structstxxl_1_1NilCase.html", null ],
    [ "noncopyable", "classstxxl_1_1noncopyable.html", "classstxxl_1_1noncopyable" ],
    [ "normal_stack", "classstxxl_1_1normal__stack.html", "classstxxl_1_1normal__stack" ],
    [ "offset_allocator", "structstxxl_1_1offset__allocator.html", "structstxxl_1_1offset__allocator" ],
    [ "onoff_switch", "classstxxl_1_1onoff__switch.html", "classstxxl_1_1onoff__switch" ],
    [ "Plug", "structstxxl_1_1Plug.html", null ],
    [ "prefetch_pool", "classstxxl_1_1prefetch__pool.html", "classstxxl_1_1prefetch__pool" ],
    [ "priority_queue", "classstxxl_1_1priority__queue.html", "classstxxl_1_1priority__queue" ],
    [ "priority_queue_config", "structstxxl_1_1priority__queue__config.html", "structstxxl_1_1priority__queue__config" ],
    [ "PRIORITY_QUEUE_GENERATOR", "classstxxl_1_1PRIORITY__QUEUE__GENERATOR.html", "classstxxl_1_1PRIORITY__QUEUE__GENERATOR" ],
    [ "queue", "classstxxl_1_1queue.html", "classstxxl_1_1queue" ],
    [ "random_number", "structstxxl_1_1random__number.html", "structstxxl_1_1random__number" ],
    [ "random_number32", "structstxxl_1_1random__number32.html", "structstxxl_1_1random__number32" ],
    [ "random_number32_r", "structstxxl_1_1random__number32__r.html", "structstxxl_1_1random__number32__r" ],
    [ "random_number64", "structstxxl_1_1random__number64.html", "structstxxl_1_1random__number64" ],
    [ "random_number8_r", "classstxxl_1_1random__number8__r.html", "classstxxl_1_1random__number8__r" ],
    [ "random_pager", "classstxxl_1_1random__pager.html", "classstxxl_1_1random__pager" ],
    [ "random_uniform_fast", "structstxxl_1_1random__uniform__fast.html", "structstxxl_1_1random__uniform__fast" ],
    [ "random_uniform_slow", "structstxxl_1_1random__uniform__slow.html", "structstxxl_1_1random__uniform__slow" ],
    [ "RC", "structstxxl_1_1RC.html", "structstxxl_1_1RC" ],
    [ "RC_disk", "structstxxl_1_1RC__disk.html", "structstxxl_1_1RC__disk" ],
    [ "RC_flash", "structstxxl_1_1RC__flash.html", "structstxxl_1_1RC__flash" ],
    [ "read_write_pool", "classstxxl_1_1read__write__pool.html", "classstxxl_1_1read__write__pool" ],
    [ "request", "classstxxl_1_1request.html", "classstxxl_1_1request" ],
    [ "request_interface", "classstxxl_1_1request__interface.html", "classstxxl_1_1request__interface" ],
    [ "request_queue", "classstxxl_1_1request__queue.html", "classstxxl_1_1request__queue" ],
    [ "request_queue_impl_1q", "classstxxl_1_1request__queue__impl__1q.html", "classstxxl_1_1request__queue__impl__1q" ],
    [ "request_queue_impl_qwqr", "classstxxl_1_1request__queue__impl__qwqr.html", "classstxxl_1_1request__queue__impl__qwqr" ],
    [ "request_queue_impl_worker", "classstxxl_1_1request__queue__impl__worker.html", "classstxxl_1_1request__queue__impl__worker" ],
    [ "request_with_state", "classstxxl_1_1request__with__state.html", "classstxxl_1_1request__with__state" ],
    [ "request_with_waiters", "classstxxl_1_1request__with__waiters.html", "classstxxl_1_1request__with__waiters" ],
    [ "resource_error", "classstxxl_1_1resource__error.html", "classstxxl_1_1resource__error" ],
    [ "row_vector", "classstxxl_1_1row__vector.html", "classstxxl_1_1row__vector" ],
    [ "run_cursor", "structstxxl_1_1run__cursor.html", "structstxxl_1_1run__cursor" ],
    [ "run_cursor2", "structstxxl_1_1run__cursor2.html", "structstxxl_1_1run__cursor2" ],
    [ "runs2bid_array_adaptor", "structstxxl_1_1runs2bid__array__adaptor.html", "structstxxl_1_1runs2bid__array__adaptor" ],
    [ "runs2bid_array_adaptor2", "structstxxl_1_1runs2bid__array__adaptor2.html", "structstxxl_1_1runs2bid__array__adaptor2" ],
    [ "scoped_mutex_lock", "classstxxl_1_1scoped__mutex__lock.html", "classstxxl_1_1scoped__mutex__lock" ],
    [ "scoped_print_timer", "classstxxl_1_1scoped__print__timer.html", "classstxxl_1_1scoped__print__timer" ],
    [ "semaphore", "classstxxl_1_1semaphore.html", "classstxxl_1_1semaphore" ],
    [ "sequence", "classstxxl_1_1sequence.html", "classstxxl_1_1sequence" ],
    [ "serving_request", "classstxxl_1_1serving__request.html", "classstxxl_1_1serving__request" ],
    [ "set_switch_handler", "classstxxl_1_1set__switch__handler.html", "classstxxl_1_1set__switch__handler" ],
    [ "settings", "classstxxl_1_1settings.html", "classstxxl_1_1settings" ],
    [ "sim_disk_file", "classstxxl_1_1sim__disk__file.html", "classstxxl_1_1sim__disk__file" ],
    [ "simdisk_geometry", "classstxxl_1_1simdisk__geometry.html", "classstxxl_1_1simdisk__geometry" ],
    [ "simple_vector", "classstxxl_1_1simple__vector.html", "classstxxl_1_1simple__vector" ],
    [ "single_disk", "structstxxl_1_1single__disk.html", "structstxxl_1_1single__disk" ],
    [ "singleton", "classstxxl_1_1singleton.html", "classstxxl_1_1singleton" ],
    [ "sorter", "classstxxl_1_1sorter.html", "classstxxl_1_1sorter" ],
    [ "SR", "structstxxl_1_1SR.html", "structstxxl_1_1SR" ],
    [ "stack_config_generator", "structstxxl_1_1stack__config__generator.html", "structstxxl_1_1stack__config__generator" ],
    [ "STACK_GENERATOR", "classstxxl_1_1STACK__GENERATOR.html", "classstxxl_1_1STACK__GENERATOR" ],
    [ "state", "classstxxl_1_1state.html", "classstxxl_1_1state" ],
    [ "stats", "classstxxl_1_1stats.html", "classstxxl_1_1stats" ],
    [ "stats_data", "classstxxl_1_1stats__data.html", "classstxxl_1_1stats__data" ],
    [ "striping", "structstxxl_1_1striping.html", "structstxxl_1_1striping" ],
    [ "swappable_block", "classstxxl_1_1swappable__block.html", "classstxxl_1_1swappable__block" ],
    [ "swappable_block_matrix", "classstxxl_1_1swappable__block__matrix.html", "classstxxl_1_1swappable__block__matrix" ],
    [ "SWITCH", "classstxxl_1_1SWITCH.html", "classstxxl_1_1SWITCH" ],
    [ "SWITCH< tag, NilCase >", "classstxxl_1_1SWITCH_3_01tag_00_01NilCase_01_4.html", "classstxxl_1_1SWITCH_3_01tag_00_01NilCase_01_4" ],
    [ "syscall_file", "classstxxl_1_1syscall__file.html", "classstxxl_1_1syscall__file" ],
    [ "timer", "classstxxl_1_1timer.html", "classstxxl_1_1timer" ],
    [ "trigger_entry_iterator", "structstxxl_1_1trigger__entry__iterator.html", "structstxxl_1_1trigger__entry__iterator" ],
    [ "tuple", "structstxxl_1_1tuple.html", "structstxxl_1_1tuple" ],
    [ "tuple< T1, Plug, Plug, Plug, Plug >", "structstxxl_1_1tuple_3_01T1_00_01Plug_00_01Plug_00_01Plug_00_01Plug_01_4.html", "structstxxl_1_1tuple_3_01T1_00_01Plug_00_01Plug_00_01Plug_00_01Plug_01_4" ],
    [ "tuple< T1, T2, Plug, Plug, Plug, Plug >", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01Plug_00_01Plug_00_01Plug_00_01Plug_01_4.html", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01Plug_00_01Plug_00_01Plug_00_01Plug_01_4" ],
    [ "tuple< T1, T2, T3, Plug, Plug, Plug >", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01Plug_00_01Plug_00_01Plug_01_4.html", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01Plug_00_01Plug_00_01Plug_01_4" ],
    [ "tuple< T1, T2, T3, T4, Plug, Plug >", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01T4_00_01Plug_00_01Plug_01_4.html", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01T4_00_01Plug_00_01Plug_01_4" ],
    [ "tuple< T1, T2, T3, T4, T5, Plug >", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01T4_00_01T5_00_01Plug_01_4.html", "structstxxl_1_1tuple_3_01T1_00_01T2_00_01T3_00_01T4_00_01T5_00_01Plug_01_4" ],
    [ "tuple_base", "structstxxl_1_1tuple__base.html", "structstxxl_1_1tuple__base" ],
    [ "tuple_greater1st", "structstxxl_1_1tuple__greater1st.html", "structstxxl_1_1tuple__greater1st" ],
    [ "tuple_less1st", "structstxxl_1_1tuple__less1st.html", "structstxxl_1_1tuple__less1st" ],
    [ "tuple_less1st_less2nd", "structstxxl_1_1tuple__less1st__less2nd.html", "structstxxl_1_1tuple__less1st__less2nd" ],
    [ "tuple_less2nd", "structstxxl_1_1tuple__less2nd.html", "structstxxl_1_1tuple__less2nd" ],
    [ "two2one_dim_array_adapter_base", "structstxxl_1_1two2one__dim__array__adapter__base.html", "structstxxl_1_1two2one__dim__array__adapter__base" ],
    [ "typed_block", "classstxxl_1_1typed__block.html", "classstxxl_1_1typed__block" ],
    [ "ufs_file_base", "classstxxl_1_1ufs__file__base.html", "classstxxl_1_1ufs__file__base" ],
    [ "uint_pair", "classstxxl_1_1uint__pair.html", "classstxxl_1_1uint__pair" ],
    [ "unordered_map", "classstxxl_1_1unordered__map.html", "classstxxl_1_1unordered__map" ],
    [ "unreachable", "classstxxl_1_1unreachable.html", "classstxxl_1_1unreachable" ],
    [ "vector", "classstxxl_1_1vector.html", "classstxxl_1_1vector" ],
    [ "vector_bufreader", "classstxxl_1_1vector__bufreader.html", "classstxxl_1_1vector__bufreader" ],
    [ "vector_bufreader_iterator", "classstxxl_1_1vector__bufreader__iterator.html", "classstxxl_1_1vector__bufreader__iterator" ],
    [ "vector_bufreader_reverse", "classstxxl_1_1vector__bufreader__reverse.html", "classstxxl_1_1vector__bufreader__reverse" ],
    [ "vector_bufwriter", "classstxxl_1_1vector__bufwriter.html", "classstxxl_1_1vector__bufwriter" ],
    [ "VECTOR_GENERATOR", "structstxxl_1_1VECTOR__GENERATOR.html", "structstxxl_1_1VECTOR__GENERATOR" ],
    [ "vector_iterator", "classstxxl_1_1vector__iterator.html", "classstxxl_1_1vector__iterator" ],
    [ "wbtl_file", "classstxxl_1_1wbtl__file.html", "classstxxl_1_1wbtl__file" ],
    [ "wfs_file_base", "classstxxl_1_1wfs__file__base.html", "classstxxl_1_1wfs__file__base" ],
    [ "wincall_file", "classstxxl_1_1wincall__file.html", "classstxxl_1_1wincall__file" ],
    [ "write_pool", "classstxxl_1_1write__pool.html", "classstxxl_1_1write__pool" ]
];