STXXL: stxxl::stream::sorted_runs< TriggerEntryType, CompareType > Struct Template Reference
stxxl::stream::sorted_runs< TriggerEntryType, CompareType > Struct Template Reference
Stream Package
Detailed Description
template<typename TriggerEntryType, typename CompareType>
struct stxxl::stream::sorted_runs< TriggerEntryType, CompareType >
All sorted runs of a sort operation.
Definition at line 37 of file sorted_runs.h.
Public Types
typedef
trigger_entry_type::block_type block_type
typedef CompareType cmp_type
typedef std::vector< run_type >
::size_type run_index_type
typedef std::vector
< trigger_entry_type > run_type
typedef stxxl::external_size_type size_type
typedef std::vector< value_type > small_run_type
typedef TriggerEntryType trigger_entry_type
typedef block_type::value_type value_type
may differ from trigger_entry_type::value_type
Public Member Functions
sorted_runs ()
~sorted_runs ()
void add_run (const run_type &run, size_type run_size)
Add a new run with given number of elements.
void clear ()
Clear the internal state of the object: release all runs and reset.
void swap (sorted_runs &b)
Swap contents with another object. This is used by the recursive merger to swap in a sorted_runs object with fewer runs.
Public Member Functions inherited from stxxl::counted_object
counted_object ()
new objects have zero reference count
counted_object (const counted_object &)
coping still creates a new object with zero reference count
~counted_object ()
bool dec_reference () const
Call whenever resetting (i.e. overwriting) a pointer to the object. IMPORTANT: In case of self-assignment, call AFTER inc_reference().
unsigned_type get_reference_count () const
Return the number of references to this object (for debugging)
void inc_reference () const
Call whenever setting a pointer to the object.
counted_object & operator= (const counted_object &)
assignment operator, leaves pointers unchanged
bool unique () const
Test if the counted_object is referenced by only one counting_ptr.
Public Attributes
size_type elements
total number of elements in all runs
std::vector< run_type > runs
vector of runs (containing vectors of block ids)
std::vector< size_type > runs_sizes
vector of the number of elements in each individual run
small_run_type small_run
Small sort optimization:
Private Member Functions
void deallocate_blocks ()
Deallocates the blocks which the runs occupy.
Private Member Functions inherited from stxxl::noncopyable
noncopyable ()
Member Typedef Documentation
template<typename TriggerEntryType , typename CompareType > typedef trigger_entry_type::block_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::block_type
Definition at line 40 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef CompareType stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::cmp_type
Definition at line 48 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef std::vector<run_type>::size_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::run_index_type
Definition at line 46 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef std::vector<trigger_entry_type> stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::run_type
Definition at line 43 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef stxxl::external_size_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::size_type
Definition at line 45 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef std::vector<value_type> stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::small_run_type
Definition at line 44 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef TriggerEntryType stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::trigger_entry_type
Definition at line 39 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > typedef block_type::value_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::value_type
may differ from trigger_entry_type::value_type
Definition at line 42 of file sorted_runs.h.
Constructor & Destructor Documentation
template<typename TriggerEntryType , typename CompareType > stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::sorted_runs () inline
Definition at line 66 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::~sorted_runs () inline
Definition at line 70 of file sorted_runs.h.
Member Function Documentation
template<typename TriggerEntryType , typename CompareType > void stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::add_run (const run_type & run, size_type run_size) inline
Add a new run with given number of elements.
Definition at line 87 of file sorted_runs.h.
template<typename TriggerEntryType , typename CompareType > void stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::clear () inline
Clear the internal state of the object: release all runs and reset.
Definition at line 76 of file sorted_runs.h.
Referenced by stxxl::stream::runs_creator< use_push< ValueType >, CompareType, BlockSize, AllocStr >::clear().
template<typename TriggerEntryType , typename CompareType > void stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::deallocate_blocks () inline private
Deallocates the blocks which the runs occupy.
Remarks
There is no need in calling this method, the blocks are deallocated by the destructor. However, if you wish to reuse the object, then this function can be used to clear its state.
Definition at line 110 of file sorted_runs.h.
References stxxl::block_manager::delete_blocks(), and stxxl::make_bid_iterator().
template<typename TriggerEntryType , typename CompareType > void stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::swap (sorted_runs< TriggerEntryType, CompareType > & b) inline
Swap contents with another object. This is used by the recursive merger to swap in a sorted_runs object with fewer runs.
Definition at line 96 of file sorted_runs.h.
References stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::elements, stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::runs, stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::runs_sizes, and stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::small_run.
Member Data Documentation
template<typename TriggerEntryType , typename CompareType > size_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::elements
total number of elements in all runs
Definition at line 51 of file sorted_runs.h.
Referenced by stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::swap().
template<typename TriggerEntryType , typename CompareType > std::vector<run_type> stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::runs
vector of runs (containing vectors of block ids)
Definition at line 54 of file sorted_runs.h.
Referenced by stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::swap().
template<typename TriggerEntryType , typename CompareType > std::vector<size_type> stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::runs_sizes
vector of the number of elements in each individual run
Definition at line 57 of file sorted_runs.h.
Referenced by stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::swap().
template<typename TriggerEntryType , typename CompareType > small_run_type stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::small_run
Small sort optimization:
Definition at line 63 of file sorted_runs.h.
Referenced by stxxl::stream::sorted_runs< TriggerEntryType, CompareType >::swap().
The documentation for this struct was generated from the following file:
include/stxxl/bits/stream/sorted_runs.h