STXXL: stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level > Struct Template Reference
stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level > Struct Template Reference
Detailed Description
template<typename ValueType, unsigned BlockSideLength, unsigned Level>
struct stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >
Definition at line 558 of file matrix_arithmetic.h.
Public Types
typedef
swappable_block_matrix_type::block_scheduler_type block_scheduler_type
typedef
block_scheduler_type::internal_block_type internal_block_type
typedef
swappable_block_matrix_type::size_type size_type
typedef matrix_to_quadtree
< ValueType, BlockSideLength,
Level-1 > smaller_matrix_to_quadtree
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
typedef static_quadtree
< ValueType, Level > vt
typedef static_quadtree< bool,
Level > zbt
Public Member Functions
matrix_to_quadtree (const swappable_block_matrix_type &matrix)
matrix_to_quadtree (const swappable_block_matrix_type &matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col)
void begin_feeding_block (const size_type &block_row, const size_type &block_col, const zbt zb)
zbt begin_reading_block (const size_type &block_row, const size_type &block_col)
void end_feeding_block (const size_type &block_row, const size_type &block_col, const zbt zb)
zbt end_reading_block (const size_type &block_row, const size_type &block_col)
void feed_and_add_element (const int_type element_num, const vt v)
void feed_element (const int_type element_num, const vt v)
const size_type & get_height_in_blocks ()
const size_type & get_width_in_blocks ()
vt read_element (const int_type element_num)
Public Attributes
smaller_matrix_to_quadtree dl
smaller_matrix_to_quadtree dr
smaller_matrix_to_quadtree ul
smaller_matrix_to_quadtree ur
Member Typedef Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef swappable_block_matrix_type::block_scheduler_type stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::block_scheduler_type
Definition at line 566 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef block_scheduler_type::internal_block_type stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::internal_block_type
Definition at line 567 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef swappable_block_matrix_type::size_type stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::size_type
Definition at line 568 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef matrix_to_quadtree<ValueType, BlockSideLength, Level - 1> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::smaller_matrix_to_quadtree
Definition at line 563 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::swappable_block_matrix_type
Definition at line 565 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef static_quadtree<ValueType, Level> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::vt
Definition at line 561 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> typedef static_quadtree<bool, Level> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::zbt
Definition at line 560 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::matrix_to_quadtree (const swappable_block_matrix_type & matrix) inline
Definition at line 572 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::matrix_to_quadtree (const swappable_block_matrix_type & matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col) inline
Definition at line 579 of file matrix_arithmetic.h.
Member Function Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level> void stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::begin_feeding_block (const size_type & block_row, const size_type & block_col, const zbt zb) inline
Definition at line 587 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> zbt stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::begin_reading_block (const size_type & block_row, const size_type & block_col) inline
Definition at line 619 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> void stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::end_feeding_block (const size_type & block_row, const size_type & block_col, const zbt zb) inline
Definition at line 611 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> zbt stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::end_reading_block (const size_type & block_row, const size_type & block_col) inline
Definition at line 639 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> void stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::feed_and_add_element (const int_type element_num, const vt v) inline
Definition at line 603 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> void stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::feed_element (const int_type element_num, const vt v) inline
Definition at line 595 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> const size_type& stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::get_height_in_blocks () inline
Definition at line 649 of file matrix_arithmetic.h.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> const size_type& stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::get_width_in_blocks () inline
Definition at line 652 of file matrix_arithmetic.h.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
template<typename ValueType, unsigned BlockSideLength, unsigned Level> vt stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::read_element (const int_type element_num) inline
Definition at line 629 of file matrix_arithmetic.h.
References stxxl::matrix_local::static_quadtree< ValueType, Level >::dl, stxxl::matrix_local::static_quadtree< ValueType, Level >::dr, stxxl::matrix_local::static_quadtree< ValueType, Level >::ul, and stxxl::matrix_local::static_quadtree< ValueType, Level >::ur.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw().
Member Data Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level> smaller_matrix_to_quadtree stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::dl
Definition at line 570 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> smaller_matrix_to_quadtree stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::dr
Definition at line 570 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> smaller_matrix_to_quadtree stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::ul
Definition at line 570 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level> smaller_matrix_to_quadtree stxxl::matrix_local::matrix_to_quadtree< ValueType, BlockSideLength, Level >::ur
Definition at line 570 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h