STXXL: stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists > Struct Template Reference
stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists > Struct Template Reference
Detailed Description
template<typename ValueType, unsigned BlockSideLength, bool AExists, bool BExists>
struct stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >
Definition at line 867 of file matrix_arithmetic.h.
Public Types
typedef
swappable_block_matrix_type::block_scheduler_type block_scheduler_type
typedef static_quadtree
< swappable_block_identifier_type, 0 > bt
typedef matrix_operations
< ValueType, BlockSideLength > Ops
typedef
swappable_block_matrix_type::size_type size_type
typedef
swappable_block_matrix_type::swappable_block_identifier_type swappable_block_identifier_type
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
Public Member Functions
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
void feed_a (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void feed_b (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void multiply ()
void read_and_add (const size_type &row, const size_type &col, swappable_block_matrix_type &bl)
Static Public Member Functions
static unsigned_type get_num_temp_grains ()
Public Attributes
swappable_block_matrix_type a
swappable_block_matrix_type b
swappable_block_matrix_type c
Member Typedef Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::block_scheduler_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::block_scheduler_type
Definition at line 870 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef static_quadtree<swappable_block_identifier_type, 0> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::bt
Definition at line 875 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef matrix_operations<ValueType, BlockSideLength> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::Ops
Definition at line 873 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::size_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::size_type
Definition at line 872 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::swappable_block_identifier_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::swappable_block_identifier_type
Definition at line 871 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::swappable_block_matrix_type
Definition at line 869 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) inline
Definition at line 879 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) inline
Definition at line 887 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) inline
Definition at line 894 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) inline
Definition at line 901 of file matrix_arithmetic.h.
Member Function Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feed_a (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) inline
Definition at line 907 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feed_b (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) inline
Definition at line 917 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> static unsigned_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::get_num_temp_grains () inline static
Definition at line 946 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::multiply () inline
Definition at line 927 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::read_and_add (const size_type & row, const size_type & col, swappable_block_matrix_type & bl) inline
Definition at line 938 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
Member Data Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::a
Definition at line 877 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::b
Definition at line 877 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::c
Definition at line 877 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h