STXXL: stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists > Struct Template Reference
stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists > Struct Template Reference
Detailed Description
template<typename ValueType, unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists>
struct stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >
Definition at line 719 of file matrix_arithmetic.h.
Public Types
typedef
swappable_block_matrix_type::block_scheduler_type block_scheduler_type
typedef
block_scheduler_type::internal_block_type internal_block_type
typedef matrix_operations
< ValueType, BlockSideLength > Ops
typedef
swappable_block_matrix_type::size_type size_type
typedef
feedable_strassen_winograd_block_grained
< ValueType, BlockSideLength,
Level-1, AExists, false > smaller_feedable_strassen_winograd_a
typedef
feedable_strassen_winograd_block_grained
< ValueType, BlockSideLength,
Level-1, AExists, BExists > smaller_feedable_strassen_winograd_ab
typedef
feedable_strassen_winograd_block_grained
< ValueType, BlockSideLength,
Level-1, false, BExists > smaller_feedable_strassen_winograd_b
typedef
feedable_strassen_winograd_block_grained
< ValueType, BlockSideLength,
Level-1, false, false > smaller_feedable_strassen_winograd_n
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
typedef static_quadtree
< ValueType, Level > vt
typedef static_quadtree< bool,
Level > zbt
Public Member Functions
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
void feed_a (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void feed_b (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void multiply ()
void read_and_add (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
Static Public Member Functions
static unsigned_type get_num_temp_grains ()
Public Attributes
const size_type l
const size_type m
const size_type n
smaller_feedable_strassen_winograd_ab p1
smaller_feedable_strassen_winograd_ab p2
smaller_feedable_strassen_winograd_n p3
smaller_feedable_strassen_winograd_n p4
smaller_feedable_strassen_winograd_n p5
smaller_feedable_strassen_winograd_b p6
smaller_feedable_strassen_winograd_a p7
Member Typedef Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef swappable_block_matrix_type::block_scheduler_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::block_scheduler_type
Definition at line 730 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef block_scheduler_type::internal_block_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::internal_block_type
Definition at line 731 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef matrix_operations<ValueType, BlockSideLength> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::Ops
Definition at line 733 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef swappable_block_matrix_type::size_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::size_type
Definition at line 732 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef feedable_strassen_winograd_block_grained<ValueType, BlockSideLength, Level - 1, AExists, false> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::smaller_feedable_strassen_winograd_a
Definition at line 725 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef feedable_strassen_winograd_block_grained<ValueType, BlockSideLength, Level - 1, AExists, BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::smaller_feedable_strassen_winograd_ab
Definition at line 724 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef feedable_strassen_winograd_block_grained<ValueType, BlockSideLength, Level - 1, false, BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::smaller_feedable_strassen_winograd_b
Definition at line 726 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef feedable_strassen_winograd_block_grained<ValueType, BlockSideLength, Level - 1, false, false> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::smaller_feedable_strassen_winograd_n
Definition at line 727 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::swappable_block_matrix_type
Definition at line 729 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef static_quadtree<ValueType, Level> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::vt
Definition at line 722 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> typedef static_quadtree<bool, Level> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::zbt
Definition at line 721 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) inline
Definition at line 741 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) inline
Definition at line 754 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) inline
Definition at line 766 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) inline
Definition at line 778 of file matrix_arithmetic.h.
Member Function Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feed_a (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) inline
Definition at line 789 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::bs, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dl, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dr, stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::is_transposed(), stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ul, and stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ur.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::feed_b (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) inline
Definition at line 810 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::bs, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dl, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dr, stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::is_transposed(), stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ul, and stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ur.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> static unsigned_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::get_num_temp_grains () inline static
Definition at line 862 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::multiply () inline
Definition at line 831 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> void stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::read_and_add (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) inline
Definition at line 842 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::bs, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dl, stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::dr, stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::is_transposed(), stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ul, and stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::swappable_block_matrix_quarterer::ur.
Member Data Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> const size_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::l
Definition at line 735 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> const size_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::m
Definition at line 735 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> const size_type stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::n
Definition at line 735 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_ab stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p1
Definition at line 736 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_ab stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p2
Definition at line 736 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_n stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p3
Definition at line 737 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_n stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p4
Definition at line 737 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_n stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p5
Definition at line 737 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_b stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p6
Definition at line 738 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Level, bool AExists, bool BExists> smaller_feedable_strassen_winograd_a stxxl::matrix_local::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, Level, AExists, BExists >::p7
Definition at line 739 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h