STXXL: stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity > Struct Template Reference
stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity > Struct Template Reference
Detailed Description
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity>
struct stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >
Definition at line 951 of file matrix_arithmetic.h.
Public Types
typedef
swappable_block_matrix_type::size_type size_type
typedef
matrix_to_quadtree_block_grained
< ValueType, BlockSideLength,
Level-1, Granularity > smaller_matrix_to_quadtree_block_grained
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
Public Member Functions
matrix_to_quadtree_block_grained (const swappable_block_matrix_type &matrix)
matrix_to_quadtree_block_grained (const swappable_block_matrix_type &matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col)
const size_type get_height ()
const size_type get_width ()
swappable_block_matrix_type operator() (const size_type &row, const size_type &col)
Public Attributes
smaller_matrix_to_quadtree_block_grained dl
smaller_matrix_to_quadtree_block_grained dr
smaller_matrix_to_quadtree_block_grained ul
smaller_matrix_to_quadtree_block_grained ur
Member Typedef Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> typedef swappable_block_matrix_type::size_type stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::size_type
Definition at line 954 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> typedef matrix_to_quadtree_block_grained<ValueType, BlockSideLength, Level - 1, Granularity> stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::smaller_matrix_to_quadtree_block_grained
Definition at line 956 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::swappable_block_matrix_type
Definition at line 953 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::matrix_to_quadtree_block_grained (const swappable_block_matrix_type & matrix) inline
Definition at line 960 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::matrix_to_quadtree_block_grained (const swappable_block_matrix_type & matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col) inline
Definition at line 967 of file matrix_arithmetic.h.
Member Function Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> const size_type stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::get_height () inline
Definition at line 980 of file matrix_arithmetic.h.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw_block_grained().
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> const size_type stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::get_width () inline
Definition at line 983 of file matrix_arithmetic.h.
Referenced by stxxl::matrix_local::matrix_operations< ValueType, BlockSideLength >::use_feedable_sw_block_grained().
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> swappable_block_matrix_type stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::operator() (const size_type & row, const size_type & col) inline
Definition at line 975 of file matrix_arithmetic.h.
Member Data Documentation
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> smaller_matrix_to_quadtree_block_grained stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::dl
Definition at line 958 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> smaller_matrix_to_quadtree_block_grained stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::dr
Definition at line 958 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> smaller_matrix_to_quadtree_block_grained stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::ul
Definition at line 958 of file matrix_arithmetic.h.
template<typename ValueType, unsigned BlockSideLength, unsigned Level, unsigned Granularity> smaller_matrix_to_quadtree_block_grained stxxl::matrix_local::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, Level, Granularity >::ur
Definition at line 958 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h