STXXL: stxxl::cmdline_parser::argument Struct Reference
stxxl::cmdline_parser::argument Struct Reference abstract
Detailed Description
base class of all options and parameters
Definition at line 49 of file cmdline.h.
Public Member Functions
argument (char key, const std::string &longkey, const std::string &keytype, const std::string &desc, bool required)
contructor filling most attributes
virtual ~argument ()
empty virtual destructor
std::string option_text () const
return '-s, –longkey [keytype]'
std::string param_text () const
return 'longkey [keytype]'
virtual void print_value (std::ostream &os) const =0
format value to ostream
virtual bool process (int &argc, const char *const *&argv)=0
process one item from command line for this argument
virtual const char * type_name () const =0
return formatted type name to user
Public Attributes
std::string m_desc
longer description, which will be wrapped
bool m_found
found during processing of command line
char m_key
single letter short option, or 0 is none
std::string m_keytype
option type description, e.g. "<#>" to indicate numbers
std::string m_longkey
long option key or name for parameters
bool m_repeated
repeated argument, i.e. std::vector<std::string>
bool m_required
required, process() fails if the option/parameter is not found.
Constructor & Destructor Documentation
stxxl::cmdline_parser::argument::argument (char key, const std::string & longkey, const std::string & keytype, const std::string & desc, bool required) inline
contructor filling most attributes
Definition at line 67 of file cmdline.h.
virtual stxxl::cmdline_parser::argument::~argument () inline virtual
empty virtual destructor
Definition at line 74 of file cmdline.h.
Member Function Documentation
std::string stxxl::cmdline_parser::argument::option_text () const inline
return '-s, –longkey [keytype]'
Definition at line 96 of file cmdline.h.
Referenced by stxxl::cmdline_parser::calc_opt_max(), stxxl::cmdline_parser::print_option_error(), stxxl::cmdline_parser::print_result(), and stxxl::cmdline_parser::print_usage().
std::string stxxl::cmdline_parser::argument::param_text () const inline
return 'longkey [keytype]'
Definition at line 86 of file cmdline.h.
Referenced by stxxl::cmdline_parser::calc_param_max(), stxxl::cmdline_parser::print_param_error(), stxxl::cmdline_parser::print_result(), and stxxl::cmdline_parser::print_usage().
virtual void stxxl::cmdline_parser::argument::print_value (std::ostream & os) const pure virtual
format value to ostream
Implemented in stxxl::cmdline_parser::argument_stringlist, stxxl::cmdline_parser::argument_string, stxxl::cmdline_parser::argument_bytes64, stxxl::cmdline_parser::argument_bytes32, stxxl::cmdline_parser::argument_uint, stxxl::cmdline_parser::argument_int, and stxxl::cmdline_parser::argument_flag.
Referenced by stxxl::cmdline_parser::print_result().
virtual bool stxxl::cmdline_parser::argument::process (int & argc, const char *const *& argv) pure virtual
process one item from command line for this argument
Implemented in stxxl::cmdline_parser::argument_stringlist, stxxl::cmdline_parser::argument_string, stxxl::cmdline_parser::argument_bytes64, stxxl::cmdline_parser::argument_bytes32, stxxl::cmdline_parser::argument_uint, stxxl::cmdline_parser::argument_int, and stxxl::cmdline_parser::argument_flag.
virtual const char* stxxl::cmdline_parser::argument::type_name () const pure virtual
return formatted type name to user
Implemented in stxxl::cmdline_parser::argument_stringlist, stxxl::cmdline_parser::argument_string, stxxl::cmdline_parser::argument_bytes64, stxxl::cmdline_parser::argument_bytes32, stxxl::cmdline_parser::argument_uint, stxxl::cmdline_parser::argument_int, and stxxl::cmdline_parser::argument_flag.
Referenced by stxxl::cmdline_parser::print_option_error(), stxxl::cmdline_parser::print_param_error(), and stxxl::cmdline_parser::print_result().
Member Data Documentation
std::string stxxl::cmdline_parser::argument::m_desc
longer description, which will be wrapped
Definition at line 58 of file cmdline.h.
Referenced by stxxl::cmdline_parser::print_usage().
bool stxxl::cmdline_parser::argument::m_found
found during processing of command line
Definition at line 62 of file cmdline.h.
char stxxl::cmdline_parser::argument::m_key
single letter short option, or 0 is none
Definition at line 52 of file cmdline.h.
std::string stxxl::cmdline_parser::argument::m_keytype
option type description, e.g. "<#>" to indicate numbers
Definition at line 56 of file cmdline.h.
std::string stxxl::cmdline_parser::argument::m_longkey
long option key or name for parameters
Definition at line 54 of file cmdline.h.
Referenced by stxxl::cmdline_parser::print_usage().
bool stxxl::cmdline_parser::argument::m_repeated
repeated argument, i.e. std::vector<std::string>
Definition at line 64 of file cmdline.h.
Referenced by stxxl::cmdline_parser::print_usage().
bool stxxl::cmdline_parser::argument::m_required
required, process() fails if the option/parameter is not found.
Definition at line 60 of file cmdline.h.
Referenced by stxxl::cmdline_parser::print_usage().
The documentation for this struct was generated from the following file:
include/stxxl/bits/common/cmdline.h